const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const scoreEl=document.getElementById('score'),messageEl=document.getElementById('message'),nextPreview=document.getElementById('nextPreview'),missionText=document.getElementById('missionText'),restartBtn=document.getElementById('restartBtn'),againBtn=document.getElementById('againBtn'),evoRow=document.getElementById('evoRow');
const W=720,H=980,WALL=24,BOUNCE=.72,MAX_SPEED=7.2,MUTUAL_G=10,BH_MAX=230,BH_START=58,BH_GROW_MS=65000,BH_RESET=.42;
const levels=[{name:'ちり',r:36,c1:'#9ca3b7',c2:'#697084'},{name:'岩',r:48,c1:'#c48b66',c2:'#7e563f'},{name:'小惑星',r:62,c1:'#c5b79b',c2:'#746b5c'},{name:'衛星',r:78,c1:'#d9e3ef',c2:'#8997a9'},{name:'惑星',r:98,c1:'#4fc8e9',c2:'#275f9d'},{name:'巨大惑星',r:121,c1:'#e9bd78',c2:'#9b6a4a'},{name:'恒星',r:148,c1:'#ffd45a',c2:'#ef6a37'},{name:'ブラックホール',r:174,c1:'#6a4bf1',c2:'#080812'}];
let balls=[],score=0,nextLevel=0,dropX=W/2,canDrop=true,gameOver=false,lastTime=0,streak=0,lastLaunchAt=0,shots=[],bgBH,flash=0,survivalMs=0,fx=null,bhMade=0,shake=0,audio=null,master=null;
function id(){return Math.random().toString(36).slice(2)+Date.now()}function massOf(b){return Math.max(1,(b.r/36)**2)}function randNext(){let r=Math.random();return r<.62?0:r<.9?1:2}function dangerSpeed(){return Math.min(2,1+Math.floor(survivalMs/60000)*.25)}
function initAudio(){if(audio)return;audio=new(window.AudioContext||window.webkitAudioContext)();master=audio.createGain();master.gain.value=.24;master.connect(audio.destination)}
function tone(f,d=.08,type='sine',v=.2,slide=1){if(!audio)return;let o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime;o.type=type;o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(Math.max(20,f*slide),t+d);g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g);g.connect(master);o.start(t);o.stop(t+d+.02)}
function noise(d=.15,v=.12){if(!audio)return;let n=Math.floor(audio.sampleRate*d),buf=audio.createBuffer(1,n,audio.sampleRate),a=buf.getChannelData(0);for(let i=0;i<n;i++)a[i]=(Math.random()*2-1)*(1-i/n);let s=audio.createBufferSource(),g=audio.createGain();s.buffer=buf;g.gain.value=v;s.connect(g);g.connect(master);s.start()}
function sfxLaunch(){tone(420,.055,'square',.10,1.7)}function sfxMerge(l){tone(180+l*45,.11,'sine',.16,1.45);if(l>=5)tone(90+l*15,.16,'triangle',.13,.72)}
function sfxBH(){tone(75,.65,'sawtooth',.22,.28);tone(680,.42,'sine',.12,.35);noise(.32,.12);navigator.vibrate?.([35,25,80])}
function sfxSave(){tone(110,.28,'sawtooth',.18,.45);setTimeout(()=>tone(520,.28,'sine',.18,1.8),120);noise(.2,.1);navigator.vibrate?.([50,30,100])}
function sfxWarning(){tone(110,.12,'square',.11,.85)}function sfxEnd(){tone(90,1.2,'sawtooth',.24,.22);noise(.8,.18);navigator.vibrate?.([120,50,180])}
function reset(){balls=[];score=0;nextLevel=randNext();dropX=W/2;canDrop=true;gameOver=false;lastTime=0;streak=0;shots=[];flash=0;survivalMs=0;fx=null;bhMade=0;shake=0;bgBH={x:W*.68,y:H*.66,r:BH_START,progress:0,hits:0};scoreEl.textContent=0;messageEl.classList.add('hidden');updateNext();missionText.textContent='連打して合体！ ブラックホールで宇宙の終わりを押し返せ！'}
function updateNext(){let l=levels[nextLevel];nextPreview.innerHTML=`<div style="width:30px;height:30px;border-radius:50%;background:${l.c1}"></div>`}function addScore(n){score+=n;scoreEl.textContent=score}
function endGame(){if(gameOver)return;gameOver=true;sfxEnd();fx={type:'end',life:1};let p=messageEl.querySelector('p');if(p)p.innerHTML=`宇宙の膨張が進み、星を作れる時代が終わりました。<br>生存 ${Math.floor(survivalMs/1000)}秒　ブラックホール ${bhMade}個<br>スコア <strong>${score}</strong>`;setTimeout(()=>messageEl.classList.remove('hidden'),900)}
function dropBall(){if(!canDrop||gameOver)return;initAudio();audio.resume?.();let now=performance.now();streak=now-lastLaunchAt<700?Math.min(16,streak+1):1;lastLaunchAt=now;let l=levels[nextLevel],x=Math.max(WALL+l.r,Math.min(W-WALL-l.r,dropX));balls.push({id:id(),x,y:WALL+l.r+8,vx:(Math.random()-.5)*1.6,vy:3.1+Math.random()*.7,r:l.r,level:nextLevel,age:0,pulse:0});shots.push({x,life:1});sfxLaunch();canDrop=false;nextLevel=randNext();updateNext();setTimeout(()=>canDrop=true,105)}
function overlap(a,b){let dx=b.x-a.x,dy=b.y-a.y,m=a.r+b.r;return dx*dx+dy*dy<m*m*1.04}
function merge(a,b){if(a.level!==b.level||a.level>=7||!overlap(a,b))return false;let ma=massOf(a),mb=massOf(b),m=ma+mb,n=a.level+1,l=levels[n],x=(a.x*ma+b.x*mb)/m,y=(a.y*ma+b.y*mb)/m;balls=balls.filter(q=>q!==a&&q!==b);balls.push({id:id(),x,y,vx:(a.vx*ma+b.vx*mb)/m,vy:(a.vy*ma+b.vy*mb)/m,r:l.r,level:n,age:0,pulse:1});addScore(Math.round((n+1)*12*(1+Math.floor(streak/4)*.4)));sfxMerge(n);if(n===7){bhMade++;fx={type:'made',x,y,life:1};flash=.8;shake=14;sfxBH()}return true}
function collide(a,b){let dx=b.x-a.x,dy=b.y-a.y,d2=dx*dx+dy*dy,m=a.r+b.r;if(d2>=m*m||!d2)return;let d=Math.sqrt(d2),nx=dx/d,ny=dy/d,o=m-d;a.x-=nx*o/2;a.y-=ny*o/2;b.x+=nx*o/2;b.y+=ny*o/2;let rv=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;if(rv<0){let j=-(1+BOUNCE)*rv/2;a.vx-=j*nx;a.vy-=j*ny;b.vx+=j*nx;b.vy+=j*ny}}
function gravity(step){for(let i=0;i<balls.length;i++)for(let j=i+1;j<balls.length;j++){let a=balls[i],b=balls[j];if(a.level<4&&b.level<4)continue;let dx=b.x-a.x,dy=b.y-a.y,d2=Math.max(1500,dx*dx+dy*dy),d=Math.sqrt(d2),f=MUTUAL_G*massOf(a)*massOf(b)/d2;a.vx+=f*dx/d/massOf(a)*step;a.vy+=f*dy/d/massOf(a)*step;b.vx-=f*dx/d/massOf(b)*step;b.vy-=f*dy/d/massOf(b)*step}}
function hitBH(){for(let b of [...balls])if(b.level===7){let dx=b.x-bgBH.x,dy=b.y-bgBH.y,r=b.r*.62+bgBH.r*.9;if(dx*dx+dy*dy<r*r){balls=balls.filter(q=>q!==b);bgBH.progress=Math.max(.04,bgBH.progress*BH_RESET);bgBH.hits++;fx={type:'save',x:bgBH.x,y:bgBH.y,life:1};flash=1;shake=20;sfxSave();addScore(1000);return}}}
function simulate(dt){if(gameOver)return;survivalMs+=dt;let step=Math.min(1.7,dt/16.67),now=performance.now();if(now-lastLaunchAt>700)streak=0;shots.forEach(s=>s.life-=.07*step);shots=shots.filter(s=>s.life>0);flash=Math.max(0,flash-.035*step);shake=Math.max(0,shake-.7*step);if(fx){fx.life-=dt/(fx.type==='end'?1000:1300);if(fx.life<=0)fx=null}bgBH.progress=Math.min(1,bgBH.progress+(dt/BH_GROW_MS)*dangerSpeed());bgBH.r=BH_START+(BH_MAX-BH_START)*bgBH.progress;if(bgBH.progress>=1){endGame();return}let left=(1-bgBH.progress)*BH_GROW_MS/dangerSpeed();if(left<10000&&Math.floor(left/1000)!==Math.floor((left+dt)/1000))sfxWarning();gravity(step);for(let b of balls){b.age+=dt;let sp=Math.hypot(b.vx,b.vy);if(sp>MAX_SPEED){b.vx*=MAX_SPEED/sp;b.vy*=MAX_SPEED/sp}b.x+=b.vx*step;b.y+=b.vy*step;if(b.x-b.r<WALL){b.x=WALL+b.r;b.vx=Math.abs(b.vx)*BOUNCE}if(b.x+b.r>W-WALL){b.x=W-WALL-b.r;b.vx=-Math.abs(b.vx)*BOUNCE}if(b.y-b.r<WALL){b.y=WALL+b.r;b.vy=Math.abs(b.vy)*BOUNCE}if(b.y+b.r>H-WALL){b.y=H-WALL-b.r;b.vy=-Math.abs(b.vy)*BOUNCE}b.pulse=Math.max(0,(b.pulse||0)-.04*step)}for(let pass=0;pass<4;pass++){let did=false;outer:for(let i=0;i<balls.length;i++)for(let j=i+1;j<balls.length;j++)if(balls[i].age>60&&balls[j].age>60&&merge(balls[i],balls[j])){did=true;break outer}if(!did)break}for(let i=0;i<balls.length;i++)for(let j=i+1;j<balls.length;j++)collide(balls[i],balls[j]);hitBH()}
function starfield(){let stage=bgBH.progress;ctx.fillStyle=stage<.72?'#070a19':stage<.9?'#120812':'#1b0508';ctx.fillRect(0,0,W,H);for(let i=0;i<120;i++){let x=(i*83+(stage>.72?survivalMs*.01:0))%W,y=(i*137)%H,a=.25+((i*29)%50)/100;ctx.fillStyle=`rgba(220,230,255,${a*(1-stage*.45)})`;ctx.fillRect(x,y,i%8?1:2,i%8?1:2)}}
function surface(b){if(b.level<=3){for(let i=0;i<4+b.level;i++){let a=(i*2.1+b.id.length)%6.28,r=b.r*(.25+(i%3)*.18),x=Math.cos(a)*r,y=Math.sin(a)*r;ctx.fillStyle='rgba(20,20,30,.15)';ctx.beginPath();ctx.arc(x,y,b.r*(.06+(i%2)*.035),0,6.28);ctx.fill()}}if(b.level===4){ctx.fillStyle='rgba(70,180,115,.38)';for(let i=0;i<4;i++){ctx.beginPath();ctx.ellipse((i-1.5)*b.r*.25,(i%2-.5)*b.r*.32,b.r*.18,b.r*.09,i,0,6.28);ctx.fill()}}if(b.level===5){ctx.strokeStyle='rgba(90,55,30,.3)';ctx.lineWidth=7;for(let y=-.5;y<=.5;y+=.25){ctx.beginPath();ctx.ellipse(0,y*b.r,b.r*.9,b.r*.18,0,0,6.28);ctx.stroke()}}}
function ring(b){if(b.level!==4&&b.level!==5)return;ctx.save();ctx.rotate(-.28);ctx.strokeStyle=b.level===5?'rgba(245,205,128,.9)':'rgba(155,225,255,.7)';ctx.lineWidth=9;ctx.beginPath();ctx.ellipse(0,0,b.r*1.34,b.r*.38,0,0,6.28);ctx.stroke();ctx.restore()}
function ball(b){let l=levels[b.level];ctx.save();ctx.translate(b.x,b.y);let p=1+(b.pulse||0)*.1;ctx.scale(p,p);let g=ctx.createRadialGradient(-b.r*.35,-b.r*.35,5,0,0,b.r);g.addColorStop(0,l.c1);g.addColorStop(1,l.c2);ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,b.r,0,6.28);ctx.fill();surface(b);ring(b);if(b.level===6){ctx.strokeStyle='rgba(255,110,35,.35)';ctx.lineWidth=8;ctx.beginPath();ctx.arc(0,0,b.r*.82,0,6.28);ctx.stroke()}if(b.level===7){ctx.fillStyle='#020208';ctx.beginPath();ctx.arc(0,0,b.r*.58,0,6.28);ctx.fill();ctx.strokeStyle='#9d7cff';ctx.lineWidth=11;ctx.beginPath();ctx.ellipse(0,0,b.r*1.05,b.r*.34,-.35,0,6.28);ctx.stroke()}ctx.restore()}
function backgroundBH(){ctx.save();ctx.translate(bgBH.x,bgBH.y);let p=bgBH.progress;ctx.shadowBlur=35+p*90;ctx.shadowColor=p>.8?'#ff304f':'#784cff';ctx.strokeStyle=p>.8?`rgba(255,70,80,${.55+p*.35})`:`rgba(160,105,255,${.5+p*.4})`;ctx.lineWidth=14+p*13;ctx.beginPath();ctx.ellipse(0,0,bgBH.r*1.2,bgBH.r*.38,-.35,0,6.28);ctx.stroke();ctx.fillStyle='#010106';ctx.beginPath();ctx.arc(0,0,bgBH.r*.7,0,6.28);ctx.fill();ctx.restore()}
function drawFx(){if(!fx)return;let t=1-fx.life,a=Math.max(0,fx.life),R=50+t*270;ctx.save();ctx.translate(fx.x||W/2,fx.y||H/2);ctx.strokeStyle=fx.type==='save'?`rgba(120,210,255,${a})`:`rgba(195,105,255,${a})`;ctx.lineWidth=14*a;ctx.beginPath();ctx.arc(0,0,R,0,6.28);ctx.stroke();ctx.textAlign='center';ctx.fillStyle=`rgba(255,255,255,${a})`;ctx.font='900 34px system-ui';ctx.fillText(fx.type==='made'?'BLACK HOLE!':fx.type==='save'?'TIME RECOVER!':'',0,-R*.55);ctx.restore()}
function draw(){ctx.save();if(shake)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);starfield();backgroundBH();shots.forEach(s=>{ctx.strokeStyle=`rgba(110,225,255,${s.life*.7})`;ctx.lineWidth=7*s.life;ctx.beginPath();ctx.moveTo(s.x,25);ctx.lineTo(s.x,140);ctx.stroke()});balls.slice().sort((a,b)=>a.level-b.level).forEach(ball);drawFx();let speed=dangerSpeed(),left=Math.max(0,Math.ceil((1-bgBH.progress)*BH_GROW_MS/speed/1000));if(left<=10){let p=.5+.5*Math.sin(performance.now()/100);ctx.fillStyle=`rgba(255,20,35,${.07+.18*p})`;ctx.fillRect(0,0,W,H);ctx.textAlign='center';ctx.fillStyle='#ff6b78';ctx.font='900 36px system-ui';ctx.fillText(`宇宙の終わりまで ${left}`,W/2,115)}ctx.fillStyle='rgba(5,5,18,.82)';ctx.fillRect(32,H-100,390,74);ctx.textAlign='left';ctx.fillStyle=left<=10?'#ff5b70':'#e8efff';ctx.font='900 19px system-ui';ctx.fillText(`宇宙の終わりまで ${left}秒`,48,H-70);ctx.font='800 15px system-ui';ctx.fillStyle='#a9baff';ctx.fillText(`生存 ${Math.floor(survivalMs/1000)}秒  ブラックホール ${bhMade}個`,48,H-46);ctx.fillStyle='#34215c';ctx.fillRect(48,H-37,350,8);ctx.fillStyle=left<=10?'#ff4f68':'#8f78ff';ctx.fillRect(48,H-37,350*bgBH.progress,8);if(streak>=4){ctx.textAlign='center';ctx.fillStyle='#dffaff';ctx.font='900 25px system-ui';ctx.fillText(`RUSH ×${streak}`,W/2,55)}ctx.restore()}
function loop(t){let dt=lastTime?Math.min(34,t-lastTime):16;lastTime=t;simulate(dt);draw();requestAnimationFrame(loop)}
function aim(e){let r=canvas.getBoundingClientRect();dropX=Math.max(60,Math.min(W-60,(e.clientX-r.left)/r.width*W));e.preventDefault()}canvas.addEventListener('pointermove',aim,{passive:false});canvas.addEventListener('pointerdown',e=>{initAudio();audio.resume?.();aim(e)},{passive:false});canvas.addEventListener('pointerup',e=>{aim(e);dropBall()},{passive:false});window.addEventListener('keydown',e=>{initAudio();audio.resume?.();if(e.key==='ArrowLeft')dropX-=28;if(e.key==='ArrowRight')dropX+=28;if(e.key===' '||e.key==='ArrowDown')dropBall()});restartBtn.onclick=reset;againBtn.onclick=reset;
evoRow.innerHTML=levels.map((l,i)=>`<div class="evoItem"><div class="evoDot" style="width:${20+i*3}px;height:${20+i*3}px;border-radius:50%;background:${l.c1}"></div><span>${l.name}</span></div>${i<7?'›':''}`).join('');reset();requestAnimationFrame(loop);