const canvas=document.getElementById('game');
const ctx=canvas.getContext('2d');
const scoreEl=document.getElementById('score');
const messageEl=document.getElementById('message');
const nextPreview=document.getElementById('nextPreview');
const missionText=document.getElementById('missionText');
const restartBtn=document.getElementById('restartBtn');
const againBtn=document.getElementById('againBtn');
const evoRow=document.getElementById('evoRow');
const W=720,H=980,WALL=24;
const BOUNCE=.72,MAX_SPEED=7.2,MUTUAL_G=10,STREAK_WINDOW=720,STREAK_MAX=12;
const BH_MAX=230,BH_START=58,BH_GROW_MS=65000,BH_RESET=.42;
const levels=[
{name:'ちり',r:36,score:1,c1:'#9ca3b7',c2:'#697084'},
{name:'岩',r:48,score:3,c1:'#c48b66',c2:'#7e563f'},
{name:'小惑星',r:62,score:8,c1:'#c5b79b',c2:'#746b5c'},
{name:'衛星',r:78,score:18,c1:'#d9e3ef',c2:'#8997a9'},
{name:'惑星',r:98,score:40,c1:'#4fc8e9',c2:'#275f9d'},
{name:'巨大惑星',r:121,score:85,c1:'#e9bd78',c2:'#9b6a4a'},
{name:'恒星',r:148,score:180,c1:'#ffd45a',c2:'#ef6a37'},
{name:'ブラックホール',r:174,score:420,c1:'#6a4bf1',c2:'#0c0c18'}];
let balls=[],score=0,nextLevel=0,dropX=W/2,canDrop=true,gameOver=false,lastTime=0,mergeLock=new Set();
let streak=0,lastLaunchAt=0,shots=[],bgBH,flash=0,survivalMs=0,createdFx=null;
function id(){return crypto.randomUUID?.()||Math.random().toString(36)}
function hash(v){let h=2166136261;for(const ch of String(v)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rand01(seed,n){const x=Math.sin((seed+n*97.13)*12.9898)*43758.5453;return x-Math.floor(x)}
function massOf(b){return Math.max(1,(b.r/36)**2)}
function randNext(){const r=Math.random();return r<.62?0:r<.9?1:2}
function streakMultiplier(){return 1+Math.min(2,Math.floor(streak/4)*.5)}
function dangerSpeed(){if(survivalMs<60000)return 1;if(survivalMs<120000)return 1.25;if(survivalMs<180000)return 1.5;if(survivalMs<240000)return 1.75;return 2}
function reset(){balls=[];score=0;dropX=W/2;nextLevel=randNext();canDrop=true;gameOver=false;mergeLock.clear();streak=0;lastLaunchAt=0;shots=[];lastTime=0;flash=0;survivalMs=0;createdFx=null;bgBH={x:W*.68,y:H*.66,r:BH_START,progress:0,hits:0};scoreEl.textContent='0';messageEl.classList.add('hidden');updateNext();updateMission()}
function updateNext(){const lv=levels[nextLevel];nextPreview.innerHTML=`<div style="width:${Math.min(34,lv.r*.5)}px;height:${Math.min(34,lv.r*.5)}px;border-radius:50%;background:radial-gradient(circle at 35% 30%,${lv.c1},${lv.c2})"></div>`}
function updateMission(){missionText.textContent='ブラックホールを作って時間を稼げ！ 長く生きるほど敵が加速する'}
function addScore(n){score+=n;scoreEl.textContent=score}
function endGame(reason){if(gameOver)return;gameOver=true;const p=messageEl.querySelector('p');if(p)p.innerHTML=`${reason}<br>生存時間 ${Math.floor(survivalMs/1000)}秒<br>最終スコア <strong>${score}</strong>`;messageEl.classList.remove('hidden')}
function dropBall(){if(!canDrop||gameOver)return;const now=performance.now();streak=(now-lastLaunchAt<STREAK_WINDOW)?Math.min(STREAK_MAX,streak+1):1;lastLaunchAt=now;const lv=levels[nextLevel],x=Math.max(WALL+lv.r,Math.min(W-WALL-lv.r,dropX));const y=WALL+lv.r+8;balls.push({id:id(),x,y,vx:(Math.random()-.5)*1.5,vy:3.05+Math.random()*.6,r:lv.r,level:nextLevel,age:0});shots.push({x,y:WALL+10,life:1});canDrop=false;nextLevel=randNext();updateNext();setTimeout(()=>canDrop=true,125)}
function isOverlapping(a,b,s=1){const dx=b.x-a.x,dy=b.y-a.y,m=a.r+b.r;return dx*dx+dy*dy<=m*m*s*s}
function merge(a,b){if(a.level!==b.level||a.level>=7)return false;const key=[a.id,b.id].sort().join(':');if(mergeLock.has(key)||!isOverlapping(a,b,1.035))return false;mergeLock.add(key);const ma=massOf(a),mb=massOf(b),t=ma+mb,nl=a.level+1,lv=levels[nl],x=(a.x*ma+b.x*mb)/t,y=(a.y*ma+b.y*mb)/t;balls=balls.filter(o=>o!==a&&o!==b);const nb={id:id(),x,y,vx:(a.vx*ma+b.vx*mb)/t,vy:(a.vy*ma+b.vy*mb)/t,r:lv.r,level:nl,age:0,pulse:1};balls.push(nb);addScore(Math.round(lv.score*streakMultiplier()));if(nl===7){createdFx={x,y,life:1};flash=Math.max(flash,.55)}return true}
function collide(a,b){const dx=b.x-a.x,dy=b.y-a.y,d2=dx*dx+dy*dy,m=a.r+b.r;if(d2>=m*m||d2===0)return;const d=Math.sqrt(d2),nx=dx/d,ny=dy/d,o=m-d,ma=massOf(a),mb=massOf(b),sum=ma+mb;a.x-=nx*o*mb/sum;a.y-=ny*o*mb/sum;b.x+=nx*o*ma/sum;b.y+=ny*o*ma/sum;const rvx=b.vx-a.vx,rvy=b.vy-a.vy,rel=rvx*nx+rvy*ny;if(rel<0){const j=-(1+BOUNCE)*rel/(1/ma+1/mb);a.vx-=j*nx/ma;a.vy-=j*ny/ma;b.vx+=j*nx/mb;b.vy+=j*ny/mb}}
function gravity(step){for(let i=0;i<balls.length;i++)for(let j=i+1;j<balls.length;j++){const a=balls[i],b=balls[j];if(a.level<4&&b.level<4)continue;const dx=b.x-a.x,dy=b.y-a.y,d2=Math.max(1200,dx*dx+dy*dy),d=Math.sqrt(d2),f=MUTUAL_G*massOf(a)*massOf(b)/d2;a.vx+=f*dx/d/massOf(a)*step;a.vy+=f*dy/d/massOf(a)*step;b.vx-=f*dx/d/massOf(b)*step;b.vy-=f*dy/d/massOf(b)*step}}
function hitBackgroundBH(){for(const b of [...balls]){if(b.level!==7)continue;const dx=b.x-bgBH.x,dy=b.y-bgBH.y;const hitR=b.r*.55+bgBH.r*.85;if(dx*dx+dy*dy<hitR*hitR){balls=balls.filter(o=>o.id!==b.id);bgBH.progress=Math.max(.05,bgBH.progress*BH_RESET);bgBH.r=BH_START+(BH_MAX-BH_START)*bgBH.progress;bgBH.hits++;flash=1;createdFx={x:bgBH.x,y:bgBH.y,life:1,collision:true};addScore(1000);return true}}return false}
function simulate(dt){if(gameOver)return;survivalMs+=dt;const step=Math.min(1.7,dt/16.67),now=performance.now();if(now-lastLaunchAt>STREAK_WINDOW)streak=0;shots.forEach(s=>{s.y+=22*step;s.life-=.08*step});shots=shots.filter(s=>s.life>0);flash=Math.max(0,flash-.035*step);if(createdFx){createdFx.life-=dt/1250;if(createdFx.life<=0)createdFx=null}bgBH.progress=Math.min(1,bgBH.progress+(dt/BH_GROW_MS)*dangerSpeed());bgBH.r=BH_START+(BH_MAX-BH_START)*bgBH.progress;if(bgBH.progress>=1){endGame('TIME UP！ 背景ブラックホールが臨界巨大化した！');return}gravity(step);balls.forEach(b=>{b.age+=dt;const sp=Math.hypot(b.vx,b.vy);if(sp>MAX_SPEED){b.vx=b.vx/sp*MAX_SPEED;b.vy=b.vy/sp*MAX_SPEED}b.x+=b.vx*step;b.y+=b.vy*step;if(b.x-b.r<WALL){b.x=WALL+b.r;b.vx=Math.abs(b.vx)*BOUNCE}if(b.x+b.r>W-WALL){b.x=W-WALL-b.r;b.vx=-Math.abs(b.vx)*BOUNCE}if(b.y-b.r<WALL){b.y=WALL+b.r;b.vy=Math.abs(b.vy)*BOUNCE}if(b.y+b.r>H-WALL){b.y=H-WALL-b.r;b.vy=-Math.abs(b.vy)*BOUNCE}if(b.pulse)b.pulse=Math.max(0,b.pulse-.045*step)});for(let pass=0;pass<4;pass++){let m=false;outer:for(let i=0;i<balls.length;i++)for(let j=i+1;j<balls.length;j++){const a=balls[i],b=balls[j];if(a.level===b.level&&a.age>65&&b.age>65&&isOverlapping(a,b,1.025)&&merge(a,b)){m=true;break outer}}if(!m)break}for(let i=0;i<balls.length;i++)for(let j=i+1;j<balls.length;j++)collide(balls[i],balls[j]);hitBackgroundBH()}
function starfield(){ctx.fillStyle='#070a19';ctx.fillRect(0,0,W,H);for(let i=0;i<110;i++){const x=(i*83)%W,y=(i*137)%H,a=.25+((i*29)%50)/100;ctx.fillStyle=`rgba(210,225,255,${a})`;ctx.fillRect(x,y,i%7===0?2:1,i%7===0?2:1)}}
function drawBackgroundBH(){ctx.save();ctx.translate(bgBH.x,bgBH.y);ctx.shadowBlur=35+bgBH.progress*80;ctx.shadowColor='#7c4dff';ctx.strokeStyle=`rgba(164,112,255,${.45+.45*bgBH.progress})`;ctx.lineWidth=14+10*bgBH.progress;ctx.beginPath();ctx.ellipse(0,0,bgBH.r*1.15,bgBH.r*.38,-.35,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#020208';ctx.beginPath();ctx.arc(0,0,bgBH.r*.7,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawSurfaceDetails(b){if(b.level===7)return;const seed=hash(b.id||b.level);ctx.save();ctx.beginPath();ctx.arc(0,0,b.r*.97,0,Math.PI*2);ctx.clip();if(b.level<=3){const n=5+b.level*2;for(let i=0;i<n;i++){const ang=rand01(seed,i)*Math.PI*2,rr=b.r*(.18+rand01(seed,i+20)*.64),x=Math.cos(ang)*rr,y=Math.sin(ang)*rr,cr=b.r*(.055+rand01(seed,i+40)*.11);ctx.fillStyle='rgba(30,25,35,.16)';ctx.beginPath();ctx.arc(x+cr*.18,y+cr*.18,cr,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.16)';ctx.lineWidth=Math.max(1,b.r*.015);ctx.beginPath();ctx.arc(x-cr*.12,y-cr*.12,cr*.82,Math.PI*.15,Math.PI*1.2);ctx.stroke()}}
if(b.level===4){ctx.strokeStyle='rgba(255,255,255,.16)';ctx.lineWidth=b.r*.08;for(let i=-2;i<=2;i++){ctx.beginPath();ctx.arc(-b.r*.65,i*b.r*.2,b.r*1.25,-.6,.55);ctx.stroke()}ctx.fillStyle='rgba(68,180,112,.42)';for(let i=0;i<5;i++){const x=(rand01(seed,i)-.5)*b.r*1.25,y=(rand01(seed,i+10)-.5)*b.r*.9;ctx.beginPath();ctx.ellipse(x,y,b.r*.18,b.r*.1,rand01(seed,i+20)*2,0,Math.PI*2);ctx.fill()}}
if(b.level===5){ctx.strokeStyle='rgba(96,63,34,.34)';for(let i=-3;i<=3;i++){ctx.lineWidth=b.r*(i%2? .055:.08);ctx.beginPath();ctx.ellipse(0,i*b.r*.19,b.r*1.25,b.r*.38,0,0,Math.PI*2);ctx.stroke()}}
if(b.level===6){for(let i=0;i<9;i++){const a=rand01(seed,i)*Math.PI*2,rr=b.r*(.18+rand01(seed,i+10)*.55),x=Math.cos(a)*rr,y=Math.sin(a)*rr,cr=b.r*(.035+rand01(seed,i+20)*.07);ctx.fillStyle='rgba(255,106,31,.25)';ctx.beginPath();ctx.arc(x,y,cr,0,Math.PI*2);ctx.fill()}}
ctx.restore()}
function drawRing(b){if(b.level!==4&&b.level!==5)return;ctx.save();ctx.rotate(-.28);ctx.strokeStyle=b.level===5?'rgba(245,205,128,.92)':'rgba(148,226,255,.72)';ctx.lineWidth=Math.max(7,b.r*.09);ctx.beginPath();ctx.ellipse(0,0,b.r*1.33,b.r*.38,0,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='rgba(255,255,255,.35)';ctx.lineWidth=Math.max(2,b.r*.018);ctx.beginPath();ctx.ellipse(0,0,b.r*1.42,b.r*.43,0,0,Math.PI*2);ctx.stroke();ctx.restore()}
function drawBall(b){const lv=levels[b.level];ctx.save();ctx.translate(b.x,b.y);const p=b.pulse?1+b.pulse*.12:1;ctx.scale(p,p);const g=ctx.createRadialGradient(-b.r*.35,-b.r*.38,b.r*.08,0,0,b.r);g.addColorStop(0,lv.c1);g.addColorStop(.72,lv.c1);g.addColorStop(1,lv.c2);ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,b.r,0,Math.PI*2);ctx.fill();drawSurfaceDetails(b);if(b.level===4||b.level===5)drawRing(b);if(b.level===7){ctx.shadowBlur=28;ctx.shadowColor='#7c4dff';ctx.fillStyle='#020208';ctx.beginPath();ctx.arc(0,0,b.r*.58,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#9d7cff';ctx.lineWidth=10;ctx.beginPath();ctx.ellipse(0,0,b.r*1.05,b.r*.35,-.35,0,Math.PI*2);ctx.stroke()}ctx.restore()}
function drawCreatedFx(){if(!createdFx)return;const t=1-createdFx.life,alpha=Math.max(0,createdFx.life),R=55+t*190;ctx.save();ctx.translate(createdFx.x,createdFx.y);ctx.strokeStyle=`rgba(185,110,255,${alpha})`;ctx.lineWidth=10*alpha;ctx.beginPath();ctx.arc(0,0,R,0,Math.PI*2);ctx.stroke();for(let i=0;i<18;i++){const a=i/18*Math.PI*2+(t*.8),r=45+t*160;ctx.fillStyle=`rgba(255,225,120,${alpha})`;ctx.beginPath();ctx.arc(Math.cos(a)*r,Math.sin(a)*r,3+5*alpha,0,Math.PI*2);ctx.fill()}ctx.textAlign='center';ctx.shadowBlur=20;ctx.shadowColor='#a759ff';ctx.fillStyle=`rgba(255,255,255,${alpha})`;ctx.font='900 34px system-ui';ctx.fillText(createdFx.collision?'TIME RECOVER!':'BLACK HOLE CREATED!',0,-R*.62);ctx.restore()}
function draw(){starfield();drawBackgroundBH();shots.forEach(s=>{ctx.strokeStyle=`rgba(115,220,255,${s.life*.75})`;ctx.lineWidth=8*s.life;ctx.beginPath();ctx.moveTo(s.x,WALL+6);ctx.lineTo(s.x,s.y);ctx.stroke()});balls.slice().sort((a,b)=>a.level-b.level).forEach(drawBall);drawCreatedFx();const speed=dangerSpeed(),effectiveMs=BH_GROW_MS/speed,left=Math.max(0,Math.ceil((1-bgBH.progress)*effectiveMs/1000));if(left<=10&&!gameOver){const pulse=.5+.5*Math.sin(performance.now()/120);ctx.fillStyle=`rgba(255,20,45,${.08+.20*pulse})`;ctx.fillRect(0,0,W,H);ctx.strokeStyle=`rgba(255,45,65,${.45+.45*pulse})`;ctx.lineWidth=10+8*pulse;ctx.strokeRect(WALL/2,WALL/2,W-WALL,H-WALL);ctx.textAlign='center';ctx.fillStyle='#ff677d';ctx.font='900 34px system-ui';ctx.fillText(`CRITICAL ${left}`,W/2,128);ctx.textAlign='left'}ctx.fillStyle='rgba(8,8,20,.78)';ctx.fillRect(WALL+8,H-100,355,72);ctx.fillStyle=left<=10?'#ff4f70':'#d7e4ff';ctx.font='900 18px system-ui';ctx.fillText(`BLACK HOLE CRITICAL: ${left}s`,WALL+20,H-70);ctx.font='800 15px system-ui';ctx.fillStyle=speed>1?'#ff9a63':'#91a7ff';ctx.fillText(`DANGER SPEED ×${speed.toFixed(2)}   SURVIVE ${Math.floor(survivalMs/1000)}s`,WALL+20,H-48);ctx.fillStyle='#25134f';ctx.fillRect(WALL+20,H-39,320,8);ctx.fillStyle=left<=10?'#ff4f70':'#8f78ff';ctx.fillRect(WALL+20,H-39,320*bgBH.progress,8);if(streak>1){ctx.textAlign='center';ctx.fillStyle='#d5f8ff';ctx.font='900 24px system-ui';ctx.fillText(`STREAK ×${streak}  MERGE ×${streakMultiplier().toFixed(1)}`,W/2,58);ctx.textAlign='left'}if(flash>0){ctx.fillStyle=`rgba(190,160,255,${flash*.32})`;ctx.fillRect(0,0,W,H)}if(!gameOver&&canDrop){const lv=levels[nextLevel],y=WALL+lv.r+8;drawBall({id:`preview-${nextLevel}`,x:dropX,y,r:lv.r,level:nextLevel})}}
function loop(t){const dt=lastTime?Math.min(34,t-lastTime):16;lastTime=t;simulate(dt);draw();requestAnimationFrame(loop)}
function pointerX(e){const rect=canvas.getBoundingClientRect();return (e.clientX-rect.left)/rect.width*W}
function moveAim(e){if(gameOver)return;dropX=Math.max(60,Math.min(W-60,pointerX(e)));if(e.cancelable)e.preventDefault()}
canvas.addEventListener('pointermove',moveAim,{passive:false});canvas.addEventListener('pointerdown',e=>moveAim(e),{passive:false});canvas.addEventListener('pointerup',e=>{moveAim(e);dropBall()},{passive:false});window.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')dropX-=28;if(e.key==='ArrowRight')dropX+=28;if(e.key===' '||e.key==='ArrowDown')dropBall();dropX=Math.max(60,Math.min(W-60,dropX))});restartBtn.addEventListener('click',reset);againBtn.addEventListener('click',reset);
function buildEvolution(){evoRow.innerHTML=levels.map((lv,i)=>`<div class="evoItem"><div class="evoDot" style="width:${20+i*3}px;height:${20+i*3}px;border-radius:50%;background:radial-gradient(circle at 35% 30%,${lv.c1},${lv.c2})"></div><span>${lv.name}</span></div>${i<levels.length-1?'›':''}`).join('')}
buildEvolution();reset();requestAnimationFrame(loop);