(()=>{
const state=[mk(),mk()];let lastTurn='',lastPhase='朝',day=1,choiceOpen=false;
function mk(){return{food:2,cap:6,path:null,days:0,pottery:false,surplus:false,hungry:false}}
const css=document.createElement('style');css.textContent=`.cultureHud{position:absolute;left:14px;top:58px;z-index:25;background:#07170fe8;border:1px solid #ffffff35;border-radius:13px;padding:8px 11px;font-weight:900;font-size:.76rem;box-shadow:0 8px 24px #0007}.cultureHud b{color:#ffe083}.cultureChoice{position:absolute;inset:0;z-index:80;display:grid;place-items:center;background:#07110bd9;backdrop-filter:blur(7px)}.cultureChoice.hidden{display:none}.cultureCard{width:min(88%,420px);padding:22px;border-radius:22px;background:#14251e;border:1px solid #ffffff35;box-shadow:0 18px 60px #000b;text-align:center}.cultureCard h2{margin:3px 0 6px}.cultureCard p{font-size:.8rem;color:#cbd8cf}.cultureOpts{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:14px}.cultureOpts button{border:1px solid #ffffff2c;border-radius:16px;padding:16px 8px;background:#203a2d;color:#fff;font-weight:900}.cultureOpts button span{display:block;font-size:2rem}.cultureOpts button small{display:block;margin-top:5px;color:#cbd8cf}.foodFlash{animation:foodFlash .7s}@keyframes foodFlash{50%{filter:brightness(1.8);transform:scale(1.08)}}`;document.head.appendChild(css);
const world=document.getElementById('world');const hud=document.createElement('div');hud.className='cultureHud';hud.id='cultureHud';world.appendChild(hud);
const chooser=document.createElement('div');chooser.className='cultureChoice hidden';chooser.innerHTML=`<div class="cultureCard"><small>CULTURE HISTORY</small><h2>この土地で、どう生きる？</h2><p>食料を手に入れる方法を選ぼう。どちらが上ではなく、自然に合わせた別の生き方です。</p><div class="cultureOpts"><button data-culture="hunt"><span>🏹</span>狩猟・採集<small>すぐ食料。収穫量は不安定</small></button><button data-culture="farm"><span>🌾</span>農耕<small>最初は少ない。後から安定</small></button></div></div>`;world.appendChild(chooser);
chooser.querySelectorAll('button').forEach(b=>b.onclick=()=>{let i=currentIndex(),s=state[i];s.path=b.dataset.culture;s.days=0;choiceOpen=false;chooser.classList.add('hidden');toast(s.path==='hunt'?'🏹 狩猟・採集の道を選んだ！':'🌾 農耕の道を選んだ！');render()});
function currentIndex(){return document.getElementById('p1Card')?.classList.contains('active')?0:1}
function toast(t){let e=document.getElementById('toast');if(!e)return;e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1500)}
function hasFire(i){let inv=document.getElementById(i?'p2Inv':'p1Inv')?.textContent||'';let mission=document.getElementById('missionNow')?.textContent||'';return !mission.includes('火を起こせ')||inv.includes('🌊')||inv.includes('🛶')}
function maybeChoice(){let i=currentIndex(),s=state[i];if(!s.path&&hasFire(i)&&!choiceOpen){choiceOpen=true;chooser.classList.remove('hidden')}}
function produce(s){s.days++;let gain=0;if(s.path==='hunt')gain=Math.random()<.25?1:Math.random()<.65?3:4;if(s.path==='farm')gain=s.days<3?1:5;s.food=Math.min(s.cap,s.food+gain);if(gain)toast(`${s.path==='hunt'?'🏹':'🌾'} 食料 +${gain}`);if(!s.pottery&&s.food>=s.cap){s.pottery=true;s.cap=12;toast('🏺 保存の工夫！ 食料庫が 6 → 12 に拡大')};if(!s.surplus&&s.food>=8){s.surplus=true;toast('✨ 食料に余裕ができた！ 舟や新しい技術へ進める')}}
function consumeDay(){day++;for(const s of state){if(s.path)produce(s);let need=2;if(s.food>=need){s.food-=need;s.hungry=false}else{s.food=0;s.hungry=true}}toast(`🌙 1日終了　🍖 食料を2消費`);render()}
function render(){let i=currentIndex(),s=state[i],path=s.path?(s.path==='hunt'?'🏹狩猟・採集':'🌾農耕'):'❓未選択';hud.innerHTML=`DAY ${day}　🍖 <b>${s.food}/${s.cap}</b>　${path}${s.hungry?'　⚠️空腹':''}`;let mn=document.getElementById('missionNow'),md=document.getElementById('missionNeed');if(!mn||!md)return;if(!s.path&&hasFire(i)){mn.textContent='🍖 食料をどう手に入れる？';md.textContent='狩猟・採集か農耕を選ぼう'}else if(s.path&&!s.pottery){mn.textContent=s.path==='hunt'?'🏹 食料を集めて暮らせ':'🌾 食料を育てて暮らせ';md.textContent=`食料 ${s.food}/${s.cap}　いっぱいになったら保存を工夫`}else if(s.pottery&&!s.surplus){mn.textContent='🏺 食料を保存せよ';md.textContent=`食料庫 ${s.food}/${s.cap}　8以上の余剰をつくろう`}else if(s.surplus&&!((document.getElementById(i?'p2Inv':'p1Inv')?.textContent||'').includes('🛶'))){mn.textContent='🛶 食料の余裕を技術へ';md.textContent='余剰ができた。水辺拠点と舟へ進もう'}if(s.hungry){mn.textContent='🍖 食料を確保せよ！';md.textContent='食料不足。次の一日までに生産しよう'}}
const turn=document.getElementById('turnText'),time=document.getElementById('timeBadge');new MutationObserver(()=>{let t=turn.textContent;if(t!==lastTurn){lastTurn=t;setTimeout(()=>{render();maybeChoice()},80)}}).observe(turn,{childList:true,subtree:true,characterData:true});new MutationObserver(()=>{let p=time.textContent;if(lastPhase.includes('晩')&&p.includes('朝'))consumeDay();lastPhase=p;render()}).observe(time,{childList:true,subtree:true,characterData:true});
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>{state[0]=mk();state[1]=mk();day=1;lastPhase='朝';render()},250)));document.getElementById('reset')?.addEventListener('click',()=>setTimeout(()=>{state[0]=mk();state[1]=mk();day=1;lastPhase='朝';render()},200));render();
})();