import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';

const N=22, HEX=.82, HSTEP=.62, BAG_MAX=6;
const DIRS=[[1,0],[-1,0],[0,1],[0,-1],[1,-1],[-1,1]];
const BASES=[[3,18],[18,18]];
const GOALS=[[3,3],[18,3]];
const phases=[
 {name:'朝',sky:0xb8d8e5,fog:0xa9c5ca,hemi:1.45,sun:2.1,sunColor:0xffd4a0,exposure:1.02},
 {name:'昼',sky:0x8fc6e3,fog:0x9bbfc8,hemi:1.7,sun:3.4,sunColor:0xfff0d0,exposure:1.08},
 {name:'晩',sky:0x24314d,fog:0x38485b,hemi:.72,sun:1.15,sunColor:0xff9360,exposure:.86}
];
const players=[
 {name:'PLAYER 1',x:3,y:18,bag:{wood:0,stone:0,sand:0},store:{wood:0,stone:0,sand:0},fire:false,harbor:false,harborPos:null,boat:false,seen:new Set()},
 {name:'COM',x:18,y:18,bag:{wood:0,stone:0,sand:0},store:{wood:0,stone:0,sand:0},fire:false,harbor:false,harborPos:null,boat:false,seen:new Set()}
];
let mode='com',turn=0,dice=0,busy=false,overview=false,seed=1,phaseIndex=0,roundCount=0;
let map=[],heightMap=[],reachable=[],reachPaths=new Map(),drag=null;
let terrain=[],colliders=[],resources=[],highlights=[],humans=[],bases=[],outposts=[],gridLines=[],dieGroup=null,riverMesh=null;
const canvas=document.getElementById('game3d'),world=document.getElementById('world'),loading=document.getElementById('loading'),errorEl=document.getElementById('webglError');
let renderer,scene,camera,raycaster,pointer=new THREE.Vector2(),clock=new THREE.Clock(),sun,hemi;
let cameraGoal=new THREE.Vector3(),lookGoal=new THREE.Vector3(),lookNow=new THREE.Vector3(),camDistance=12;

boot();
function boot(){try{if(!document.createElement('canvas').getContext('webgl2'))throw new Error('WebGL2 unavailable');init3D();bindUI();renderLoop();loading.classList.add('hidden')}catch(e){console.error(e);loading.classList.add('hidden');errorEl.textContent='3D表示を開始できませんでした: '+e.message;errorEl.classList.remove('hidden')}}
function init3D(){renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.35));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(42,1,.1,140);raycaster=new THREE.Raycaster();hemi=new THREE.HemisphereLight(0xe8f5ff,0x243324,1.5);scene.add(hemi);sun=new THREE.DirectionalLight(0xffefd2,3);sun.position.set(-14,24,10);sun.castShadow=true;sun.shadow.mapSize.set(1536,1536);sun.shadow.camera.left=-32;sun.shadow.camera.right=32;sun.shadow.camera.top=32;sun.shadow.camera.bottom=-32;sun.shadow.camera.far=85;scene.add(sun);const floor=new THREE.Mesh(new THREE.PlaneGeometry(120,120),new THREE.MeshStandardMaterial({color:0x294839,roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.46;floor.receiveShadow=true;scene.add(floor);applyPhase();resize();window.addEventListener('resize',resize)}
const MAT={grass:new THREE.MeshStandardMaterial({color:0x648c4e,roughness:.98}),valley:new THREE.MeshStandardMaterial({color:0x4b7240,roughness:1}),sand:new THREE.MeshStandardMaterial({color:0xd1b76d,roughness:1}),rock:new THREE.MeshStandardMaterial({color:0x817a6d,roughness:1}),mountain:new THREE.MeshStandardMaterial({color:0x817f77,roughness:1}),cliff:new THREE.MeshStandardMaterial({color:0x67655f,roughness:1}),pass:new THREE.MeshStandardMaterial({color:0x7c7f58,roughness:1}),goal:new THREE.MeshStandardMaterial({color:0x579d9a,roughness:.9}),water:new THREE.MeshPhysicalMaterial({color:0x327fa0,roughness:.16,transparent:true,opacity:.89,clearcoat:.7}),river:new THREE.MeshPhysicalMaterial({color:0x4fa6c0,roughness:.13,transparent:true,opacity:.95,clearcoat:.75})};
function rng(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}function rand(a,b){return a+Math.floor(rng()*(b-a+1))}function inside(x,y){return x>=0&&y>=0&&x<N&&y<N}function key(x,y){return `${x},${y}`}function hdist(a,b,c,d){let dx=c-a,dy=d-b;return(Math.abs(dx)+Math.abs(dy)+Math.abs(dx+dy))/2}function elevation(x,y){return heightMap[y]?.[x]??0}function pos(x,y){return new THREE.Vector3((x+y*.5)*HEX*1.73,0,y*HEX*1.5)}function topY(x,y){return elevation(x,y)*HSTEP}function bagCount(p){return p.bag.wood+p.bag.stone+p.bag.sand}function isBase(i,x,y){return BASES[i][0]===x&&BASES[i][1]===y}function isWaterTile(x,y){return map[y]?.[x]==='river'||map[y]?.[x]==='water'}
function isWaterside(x,y){if(isWaterTile(x,y)||map[y]?.[x]==='goal')return false;return DIRS.some(([dx,dy])=>inside(x+dx,y+dy)&&isWaterTile(x+dx,y+dy))}
function generateWorld(){seed=(Date.now()^Math.floor(Math.random()*1e9))>>>0;map=Array.from({length:N},()=>Array(N).fill('grass'));heightMap=Array.from({length:N},()=>Array(N).fill(1));for(let y=0;y<N;y++)for(let x=0;x<N;x++){let e=Math.min(x,y,N-1-x,N-1-y);if(e===0||(e===1&&rng()<.58)){map[y][x]='water';heightMap[y][x]=0}}for(let b=0;b<6;b++){let cx=rand(4,N-5),cy=rand(4,N-7),r=rand(2,4),peak=rand(3,5);for(let y=1;y<N-1;y++)for(let x=1;x<N-1;x++){let d=Math.hypot((x-cx)*.9,y-cy);if(d<r)heightMap[y][x]=Math.max(heightMap[y][x],Math.max(2,Math.round(peak-d/r*2.3)))}}let rx=rand(7,N-8);for(let y=1;y<N-1;y++){rx=Math.max(3,Math.min(N-4,rx+rand(-1,1)));map[y][rx]='river';heightMap[y][rx]=0;if(rng()<.32&&rx+1<N-1){map[y][rx+1]='river';heightMap[y][rx+1]=0}}for(let y=1;y<N-1;y++)for(let x=1;x<N-1;x++){if(map[y][x]==='river')continue;let h=elevation(x,y);if(h>=4)map[y][x]='mountain';else if(h===3)map[y][x]='cliff';else if(h===2&&rng()<.55)map[y][x]='valley'}for(const[sx,sy]of BASES){for(let y=sy-2;y<=sy+1;y++)for(let x=sx-2;x<=sx+2;x++)if(inside(x,y)&&!isWaterTile(x,y)){map[y][x]='grass';heightMap[y][x]=1}map[sy][sx]='grass';heightMap[sy][sx]=1}for(let i=0;i<27;i++)place('tree');for(let i=0;i<18;i++)place('rock');for(let i=0;i<14;i++)place('sand');let passes=0;for(let y=1;y<N-1;y++)for(let x=1;x<N-1;x++)if((map[y][x]==='mountain'||map[y][x]==='cliff')&&rng()<.13){map[y][x]='pass';heightMap[y][x]=Math.max(2,elevation(x,y));passes++}if(passes<3){[[6,7],[12,8],[16,11]].forEach(([x,y])=>{map[y][x]='pass';heightMap[y][x]=2})}for(const[gx,gy]of GOALS){for(let y=gy-1;y<=gy+1;y++)for(let x=gx-1;x<=gx+1;x++)if(inside(x,y)){map[y][x]='water';heightMap[y][x]=0}map[gy][gx]='goal';heightMap[gy][gx]=1}for(let i=0;i<2;i++){ensureNear(BASES[i][0],BASES[i][1],'tree');ensureNear(BASES[i][0],BASES[i][1],'rock')}}
function place(t){for(let i=0;i<120;i++){let x=rand(1,N-2),y=rand(1,N-2);if(map[y][x]==='grass'||map[y][x]==='valley'){map[y][x]=t;return}}}function ensureNear(sx,sy,t){for(let y=Math.max(1,sy-4);y<=Math.min(N-2,sy);y++)for(let x=Math.max(1,sx-4);x<=Math.min(N-2,sx+4);x++)if(map[y][x]===t)return;let x=Math.max(1,Math.min(N-2,sx+(rng()<.5?-2:2))),y=Math.max(1,sy-2);map[y][x]=t;heightMap[y][x]=1}
function clearWorld(){for(const o of [...terrain,...colliders,...resources,...highlights,...humans,...bases,...outposts,...gridLines])scene.remove(o);if(riverMesh)scene.remove(riverMesh);if(dieGroup)scene.remove(dieGroup);terrain=[];colliders=[];resources=[];highlights=[];humans=[];bases=[];outposts=[];gridLines=[];riverMesh=null;dieGroup=null}
function buildWorld(){clearWorld();for(let y=0;y<N;y++)for(let x=0;x<N;x++){addTerrain(x,y);addCollider(x,y);addResource(x,y);addHighlight(x,y);addBorder(x,y)}addRiver();BASES.forEach((b,i)=>addBase(i,b[0],b[1]));humans=[makeTraveler(0),makeTraveler(1)];scene.add(...humans);updateHumans();reveal(players[0]);reveal(players[1]);updateFog()}
function terrainMaterial(t){if(t==='tree'||t==='rock')return MAT.grass;if(t==='sand')return MAT.sand;return MAT[t]||MAT.grass}
function addTerrain(x,y){let t=map[y][x],p=pos(x,y),h=topY(x,y);if(t==='water'){let m=new THREE.Mesh(new THREE.CylinderGeometry(.94,.98,.08,24),MAT.water.clone());m.position.set(p.x,.02,p.z);m.receiveShadow=true;m.userData={x,y,type:t};scene.add(m);terrain.push(m);return}let high=t==='mountain'||t==='cliff',topR=high?.82:.91,bottomR=t==='mountain'?1.12:t==='cliff'?1.04:.96,base=Math.max(-.12,h-(t==='mountain'?1.8:t==='cliff'?1.45:.68)),depth=Math.max(.26,h-base+.14),geo=new THREE.CylinderGeometry(topR,bottomR,depth,t==='mountain'?12:18,3,false),m=new THREE.Mesh(geo,terrainMaterial(t).clone());m.position.set(p.x,base+depth/2,p.z);m.castShadow=true;m.receiveShadow=true;m.userData={x,y,type:t};if(t==='mountain'){m.scale.y=1.15;m.rotation.y=(x*7+y*3)*.09}if(t==='sand'){m.scale.y=.9;addDunes(p.x,h+.08,p.z)}scene.add(m);terrain.push(m)}
function addDunes(x,y,z){for(let i=0;i<2;i++){let d=new THREE.Mesh(new THREE.TorusGeometry(.3+i*.06,.04,6,20,Math.PI),new THREE.MeshStandardMaterial({color:0xb99b59,roughness:1}));d.rotation.x=Math.PI/2;d.rotation.z=i?.45:-.25;d.position.set(x+(i?-.18:.16),y+.03,z+(i?.08:-.08));scene.add(d);resources.push(d)}}
function addCollider(x,y){let p=pos(x,y),g=new THREE.CylinderGeometry(.79,.79,.1,6);g.rotateY(Math.PI/6);let m=new THREE.Mesh(g,new THREE.MeshBasicMaterial({transparent:true,opacity:.002,depthWrite:false}));m.position.set(p.x,topY(x,y)+.08,p.z);m.userData={x,y};scene.add(m);colliders.push(m)}
function addBorder(x,y){let p=pos(x,y),shape=[];for(let i=0;i<7;i++){let a=Math.PI/6+i*Math.PI/3;shape.push(new THREE.Vector3(p.x+Math.cos(a)*.79,topY(x,y)+.15,p.z+Math.sin(a)*.79))}let line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(shape),new THREE.LineBasicMaterial({color:0x263b2d,transparent:true,opacity:.55}));line.userData={x,y};scene.add(line);gridLines.push(line)}
function addHighlight(x,y){let p=pos(x,y),r=new THREE.Mesh(new THREE.RingGeometry(.48,.68,24),new THREE.MeshBasicMaterial({color:0xffdf56,transparent:true,opacity:0,side:THREE.DoubleSide,depthWrite:false}));r.rotation.x=-Math.PI/2;r.position.set(p.x,topY(x,y)+.14,p.z);r.userData={x,y};scene.add(r);highlights.push(r)}
function addResource(x,y){let t=map[y][x],p=pos(x,y),y0=topY(x,y)+.1;if(t==='tree'){let g=new THREE.Group();g.userData={x,y};for(let j=0;j<2;j++){let trunk=new THREE.Mesh(new THREE.CylinderGeometry(.06,.09,.42,7),new THREE.MeshStandardMaterial({color:0x60422e}));trunk.position.set((j-.5)*.2,.21,(j-.5)*.12);let crown=new THREE.Mesh(new THREE.ConeGeometry(.29,.65,8),new THREE.MeshStandardMaterial({color:j?0x2e6d3d:0x275f35}));crown.position.set((j-.5)*.2,.68,(j-.5)*.12);g.add(trunk,crown)}g.position.set(p.x,y0,p.z);g.traverse(o=>{if(o.isMesh)o.castShadow=true});scene.add(g);resources.push(g)}else if(t==='rock'){let r=new THREE.Mesh(new THREE.DodecahedronGeometry(.28,1),new THREE.MeshStandardMaterial({color:0x89857e}));r.position.set(p.x,y0+.2,p.z);r.scale.set(1.3,.75,1);r.castShadow=true;r.userData={x,y};scene.add(r);resources.push(r)}else if(t==='goal'){let g=new THREE.Group();g.userData={x,y};let pole=new THREE.Mesh(new THREE.CylinderGeometry(.04,.04,.9,8),new THREE.MeshStandardMaterial({color:0xf4d65c}));pole.position.y=.45;let star=new THREE.Mesh(new THREE.OctahedronGeometry(.18),new THREE.MeshStandardMaterial({color:0xffe56b,emissive:0x7b5d00,emissiveIntensity:.5}));star.position.y=1;g.add(pole,star);g.position.set(p.x,y0,p.z);scene.add(g);resources.push(g)}}
function addRiver(){let pts=[];for(let y=0;y<N;y++){let xs=[];for(let x=0;x<N;x++)if(map[y][x]==='river')xs.push(x);if(xs.length){let x=xs.reduce((a,b)=>a+b,0)/xs.length,p=pos(x,y);pts.push(new THREE.Vector3(p.x,.06,p.z))}}if(pts.length>2){let curve=new THREE.CatmullRomCurve3(pts);riverMesh=new THREE.Mesh(new THREE.TubeGeometry(curve,120,.27,10,false),MAT.river);scene.add(riverMesh)}}
function addBase(i,x,y){let p=pos(x,y),g=new THREE.Group();g.userData={base:true,owner:i,x,y};let pad=new THREE.Mesh(new THREE.CylinderGeometry(.58,.66,.14,10),new THREE.MeshStandardMaterial({color:i?0x335c91:0x8b433b}));pad.position.y=.07;let tent=new THREE.Mesh(new THREE.ConeGeometry(.35,.62,4),new THREE.MeshStandardMaterial({color:i?0x567fb2:0xc06656}));tent.position.y=.43;tent.rotation.y=Math.PI/4;let crate=new THREE.Mesh(new THREE.BoxGeometry(.25,.22,.25),new THREE.MeshStandardMaterial({color:0x735336}));crate.position.set(.42,.14,.12);g.add(pad,tent,crate);g.position.set(p.x,topY(x,y)+.11,p.z);g.traverse(o=>{if(o.isMesh)o.castShadow=true});scene.add(g);bases.push(g)}
function addWatersideBase(i,x,y){let p=pos(x,y),g=new THREE.Group(),wood=new THREE.MeshStandardMaterial({color:0x76502f,roughness:1}),cloth=new THREE.MeshStandardMaterial({color:i?0x6c9bd6:0xd47a65,roughness:1});let deck=new THREE.Mesh(new THREE.BoxGeometry(.92,.09,.48),wood);deck.position.y=.06;let post1=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,.55,6),wood),post2=post1.clone();post1.position.set(-.3,.28,0);post2.position.set(.3,.28,0);let flag=new THREE.Mesh(new THREE.PlaneGeometry(.35,.22),cloth);flag.position.set(.16,.45,0);flag.rotation.y=Math.PI/2;let crate=new THREE.Mesh(new THREE.BoxGeometry(.24,.2,.24),wood);crate.position.set(-.25,.18,.05);g.add(deck,post1,post2,flag,crate);g.position.set(p.x,topY(x,y)+.13,p.z);g.userData={outpost:true,owner:i,x,y};g.traverse(o=>{if(o.isMesh)o.castShadow=true});scene.add(g);outposts.push(g)}
function makeTraveler(i){let root=new THREE.Group(),human=new THREE.Group(),shirt=new THREE.MeshStandardMaterial({color:i?0x4b87ea:0xe94f45}),skin=new THREE.MeshStandardMaterial({color:0xe3ad87}),torso=new THREE.Mesh(new THREE.CylinderGeometry(.13,.16,.42,8),shirt),head=new THREE.Mesh(new THREE.SphereGeometry(.13,10,8),skin),leg1=new THREE.Mesh(new THREE.CylinderGeometry(.045,.045,.29,7),shirt),leg2=leg1.clone(),bag=new THREE.Mesh(new THREE.BoxGeometry(.2,.26,.13),new THREE.MeshStandardMaterial({color:0x705235}));torso.position.y=.47;head.position.y=.8;leg1.position.set(-.07,.14,0);leg2.position.set(.07,.14,0);bag.position.set(0,.47,-.15);human.add(torso,head,leg1,leg2,bag);let boat=new THREE.Group(),hullMat=new THREE.MeshStandardMaterial({color:i?0x365e8a:0x8b4b35,roughness:.78}),hull=new THREE.Mesh(new THREE.SphereGeometry(.48,14,8,0,Math.PI*2,Math.PI*.5,Math.PI*.5),hullMat);hull.scale.set(1.25,.35,.58);hull.rotation.z=Math.PI;hull.position.y=.12;let bow=new THREE.Mesh(new THREE.ConeGeometry(.26,.55,8),hullMat);bow.rotation.z=-Math.PI/2;bow.position.set(.5,.12,0);let mast=new THREE.Mesh(new THREE.CylinderGeometry(.025,.025,.55,6),new THREE.MeshStandardMaterial({color:0x6b4a2c}));mast.position.y=.42;let sail=new THREE.Mesh(new THREE.PlaneGeometry(.38,.38),new THREE.MeshStandardMaterial({color:i?0xdbe8ff:0xffe0c8,side:THREE.DoubleSide,roughness:.8}));sail.position.set(.16,.5,0);sail.rotation.y=Math.PI/2;boat.add(hull,bow,mast,sail);boat.visible=false;root.add(human,boat);root.userData={human,boat,leg1,leg2,bag};root.traverse(o=>{if(o.isMesh)o.castShadow=true});return root}
function setTravelerMode(i,x,y){let g=humans[i],water=isWaterTile(x,y);g.userData.human.visible=!water;g.userData.boat.visible=water;return water}
function updateHumans(){players.forEach((p,i)=>{let v=pos(p.x,p.y),water=setTravelerMode(i,p.x,p.y);humans[i].position.set(v.x,water?.13:topY(p.x,p.y)+.15,v.z);let fill=bagCount(p)/BAG_MAX;humans[i].userData.bag.scale.set(1,1+.35*fill,1)})}
function reveal(p){for(let y=0;y<N;y++)for(let x=0;x<N;x++)if(hdist(p.x,p.y,x,y)<=5)p.seen.add(key(x,y))}
function updateFog(){let v=players[turn];for(const m of terrain){let{x,y,type}=m.userData,seen=v.seen.has(key(x,y)),near=hdist(v.x,v.y,x,y)<=5;m.visible=seen;if(m.material){m.material.transparent=!near||type==='water';m.material.opacity=near?(type==='water'?.89:1):(type==='water'?.36:.46);m.material.depthWrite=near&&type!=='water'}}for(const r of resources){let d=r.userData;if(d&&Number.isFinite(d.x))r.visible=v.seen.has(key(d.x,d.y))}for(const c of colliders)c.visible=v.seen.has(key(c.userData.x,c.userData.y));for(const l of gridLines){let{x,y}=l.userData;l.visible=v.seen.has(key(x,y));l.material.opacity=hdist(v.x,v.y,x,y)<=5?.55:.24}for(const o of outposts)o.visible=v.seen.has(key(o.userData.x,o.userData.y))}
function bindUI(){document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>startGame(b.dataset.mode));document.getElementById('backToTitle').onclick=()=>{document.getElementById('gameApp').classList.add('game-hidden');document.getElementById('titleScreen').style.display='grid'};document.getElementById('reset').onclick=resetGame;document.getElementById('playAgain').onclick=resetGame;document.getElementById('diceBtn').onclick=roll;document.getElementById('overviewBtn').onclick=()=>{overview=!overview;overview?showOverview():focusPlayer(turn)};canvas.addEventListener('pointerdown',pointerDown);canvas.addEventListener('pointermove',pointerMove);canvas.addEventListener('pointerup',pointerUp);canvas.addEventListener('pointercancel',pointerUp)}
function startGame(m){mode=m;players[1].name=m==='com'?'COM':'PLAYER 2';document.getElementById('p2Name').textContent=players[1].name;document.getElementById('titleScreen').style.display='none';document.getElementById('gameApp').classList.remove('game-hidden');requestAnimationFrame(()=>{resize();resetGame()})}
function resetGame(){generateWorld();players.forEach((p,i)=>{p.x=BASES[i][0];p.y=BASES[i][1];p.bag={wood:0,stone:0,sand:0};p.store={wood:0,stone:0,sand:0};p.fire=false;p.harbor=isWaterside(p.x,p.y);p.harborPos=p.harbor?{x:p.x,y:p.y}:null;p.boat=false;p.seen=new Set()});turn=0;dice=0;busy=false;overview=false;phaseIndex=0;roundCount=0;reachable=[];reachPaths.clear();let d=document.getElementById('winDialog');if(d.open)d.close();applyPhase();buildWorld();updateHud();focusPlayer(0,true);if(players[0].harbor)toast('🌊 水辺スタート！ 水辺拠点ミッションをクリア');else toast('🏕️ 広い世界へ出発！')}
function applyPhase(){let p=phases[phaseIndex];scene.background=new THREE.Color(p.sky);scene.fog=new THREE.FogExp2(p.fog,.018);hemi.intensity=p.hemi;sun.intensity=p.sun;sun.color.setHex(p.sunColor);renderer.toneMappingExposure=p.exposure;document.getElementById('timeBadge').textContent=`${phaseIndex===0?'🌅':phaseIndex===1?'☀️':'🌙'} ${p.name}`}
function focusPlayer(i=turn,instant=false){let p=players[i],v=pos(p.x,p.y),h=isWaterTile(p.x,p.y)?.2:topY(p.x,p.y);lookGoal.set(v.x,h+.3,v.z);cameraGoal.set(v.x+camDistance*.68,7+camDistance*.2,v.z+camDistance*.82);if(instant){camera.position.copy(cameraGoal);lookNow.copy(lookGoal);camera.lookAt(lookNow)}document.getElementById('cameraLabel').textContent=`📍 ${p.name}`}
function showOverview(){let v=pos((N-1)/2,(N-1)/2);lookGoal.set(v.x,1,v.z);cameraGoal.set(v.x+26,28,v.z+32);document.getElementById('cameraLabel').textContent='🗺️'}function resize(){let r=world.getBoundingClientRect();if(r.width<2||r.height<2)return;renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}
function canEnter(p,x,y,from){if(!inside(x,y))return false;let t=map[y][x],ft=map[from.y][from.x],dh=elevation(x,y)-elevation(from.x,from.y);if(t==='river'||t==='water'||t==='goal')return p.boat;if(t==='cliff'&&ft!=='pass')return false;if(Math.abs(dh)>=2&&t!=='pass'&&ft!=='pass')return false;if(t==='mountain'&&ft!=='pass'&&ft!=='mountain')return false;return true}
function getReachable(p,steps){let q=[{x:p.x,y:p.y,d:0,path:[]}],seenStates=new Set([`${p.x},${p.y},0`]),destinations=new Map();reachPaths.clear();while(q.length){let cur=q.shift();if(cur.d===steps){let k=key(cur.x,cur.y);if(cur.x!==p.x||cur.y!==p.y){if(!destinations.has(k))destinations.set(k,{x:cur.x,y:cur.y,d:cur.d,path:cur.path})}continue}for(const[dx,dy]of DIRS){let x=cur.x+dx,y=cur.y+dy;if(!canEnter(p,x,y,cur))continue;let nd=cur.d+1,stateKey=`${x},${y},${nd}`;if(seenStates.has(stateKey))continue;seenStates.add(stateKey);q.push({x,y,d:nd,path:[...cur.path,{x,y}]})}}let out=[...destinations.values()];for(const r of out)reachPaths.set(key(r.x,r.y),r.path);return out}
async function roll(){if(busy||dice||(mode==='com'&&turn===1))return;busy=true;let n=rand(1,6);await animateDie(n);dice=n;reachable=getReachable(players[turn],n);showHighlights();busy=false;if(!reachable.length)setTimeout(endTurn,450)}
function dieTexture(n){let c=document.createElement('canvas');c.width=c.height=128;let g=c.getContext('2d');g.fillStyle='#fffaf0';g.fillRect(0,0,128,128);g.fillStyle='#181818';let P=[[64,64],[36,36],[92,92],[92,36],[36,92],[36,64],[92,64]],idx={1:[0],2:[1,2],3:[1,0,2],4:[1,3,4,2],5:[1,3,0,4,2],6:[1,5,4,3,6,2]}[n];for(const i of idx){g.beginPath();g.arc(P[i][0],P[i][1],11,0,Math.PI*2);g.fill()}let t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function makeDie(){if(dieGroup)scene.remove(dieGroup);dieGroup=new THREE.Group();let mats=[];for(let i=1;i<=6;i++)mats.push(new THREE.MeshStandardMaterial({map:dieTexture(i),roughness:.38}));let cube=new THREE.Mesh(new THREE.BoxGeometry(.72,.72,.72),mats);cube.castShadow=true;dieGroup.add(cube);scene.add(dieGroup);return cube}
function resultEuler(n){switch(n){case 1:return new THREE.Euler(0,0,Math.PI/2);case 2:return new THREE.Euler(0,0,-Math.PI/2);case 3:return new THREE.Euler(0,0,0);case 4:return new THREE.Euler(Math.PI,0,0);case 5:return new THREE.Euler(-Math.PI/2,0,0);case 6:return new THREE.Euler(Math.PI/2,0,0);default:return new THREE.Euler()}}
function animateDie(n){return new Promise(resolve=>{let cube=makeDie(),p=players[turn],v=pos(p.x,p.y),base=isWaterTile(p.x,p.y)?.2:topY(p.x,p.y),t0=performance.now(),dur=1050,settle=380;dieGroup.position.set(v.x-.9,base+2,v.z+.4);function step(now){let t=Math.min(1,(now-t0)/dur),hop=Math.abs(Math.sin(t*Math.PI*4.5))*(1-t)*1.5;dieGroup.position.set(v.x-.9+t*2.7,base+.4+hop,v.z+.4+t);cube.rotation.x+=.26;cube.rotation.y+=.33;cube.rotation.z+=.21;if(t<1){requestAnimationFrame(step)}else{let from=cube.quaternion.clone(),targetQ=new THREE.Quaternion().setFromEuler(resultEuler(n)),s0=performance.now();function settleStep(ts){let s=Math.min(1,(ts-s0)/settle),e=1-Math.pow(1-s,3);cube.quaternion.slerpQuaternions(from,targetQ,e);dieGroup.position.y=base+.42+Math.sin(s*Math.PI)*.08*(1-s);if(s<1)requestAnimationFrame(settleStep);else{toast(`🎲 ${n}`);setTimeout(()=>{scene.remove(dieGroup);dieGroup=null;resolve()},520)}}requestAnimationFrame(settleStep)}}requestAnimationFrame(step)})}
function showHighlights(){let set=new Set(reachable.map(r=>key(r.x,r.y)));for(const h of highlights)h.material.opacity=set.has(key(h.userData.x,h.userData.y))?.82:0}
async function moveTo(x,y){if(busy||!reachable.some(r=>r.x===x&&r.y===y))return;busy=true;let who=turn,p=players[who],path=reachPaths.get(key(x,y))||[{x,y}];reachable=[];showHighlights();for(const s of path){let wasWater=isWaterTile(p.x,p.y),willWater=isWaterTile(s.x,s.y);p.x=s.x;p.y=s.y;reveal(p);if(willWater&&!wasWater)toast('🛶 舟に乗った！');if(!willWater&&wasWater)toast('🚶 上陸！');await travelStep(who,s.x,s.y,willWater);updateFog()}collect(p,x,y);if(isBase(who,x,y))depositAtBase(p);maybeBuildWatersideBase(p,who,x,y);autoCraft(p);updateHumans();updateHud();busy=false;if(map[y][x]==='goal'){win();return}setTimeout(endTurn,450)}
function travelStep(i,x,y,water){return new Promise(resolve=>{let g=humans[i],from=g.position.clone(),v=pos(x,y),to=new THREE.Vector3(v.x,water?.13:topY(x,y)+.15,v.z),t0=performance.now(),dur=water?360:290;setTravelerMode(i,x,y);let dx=to.x-from.x,dz=to.z-from.z;g.rotation.y=Math.atan2(dz,dx);function step(now){let t=Math.min(1,(now-t0)/dur),e=t*t*(3-2*t);g.position.lerpVectors(from,to,e);if(water){g.position.y=to.y+Math.sin(t*Math.PI*3)*.035;g.rotation.z=Math.sin(t*Math.PI*2)*.035}else{g.userData.leg1.rotation.x=Math.sin(t*Math.PI*4)*.6;g.userData.leg2.rotation.x=-Math.sin(t*Math.PI*4)*.6}if(t<1)requestAnimationFrame(step);else{g.rotation.z=0;g.userData.leg1.rotation.x=g.userData.leg2.rotation.x=0;focusPlayer(i);resolve()}}requestAnimationFrame(step)})}
function collect(p,x,y){let t=map[y][x],item=t==='tree'?'wood':t==='rock'?'stone':t==='sand'?'sand':null;if(!item)return;if(bagCount(p)>=BAG_MAX){toast('🎒 リュックがいっぱい！ 基地へ戻ろう');return}p.bag[item]++;toast(`${item==='wood'?'🪵':item==='stone'?'🪨':'⌛'} リュックへ +1`)}
function depositAtBase(p){let n=bagCount(p);if(!n)return;for(const k of['wood','stone','sand']){p.store[k]+=p.bag[k];p.bag[k]=0}toast(`🏕️ 基地に ${n}個 保管！`)}
function maybeBuildWatersideBase(p,i,x,y){if(!p.fire||p.harbor||!isWaterside(x,y))return;p.harbor=true;p.harborPos={x,y};addWatersideBase(i,x,y);toast('🏕️🌊 水辺拠点を建設！ 舟を作れるようになった')}
function autoCraft(p){if(!p.fire&&p.store.wood>=2&&p.store.stone>=1){p.store.wood-=2;p.store.stone--;p.fire=true;toast('🔥 基地で火を発明！')}if(p.fire&&p.harbor&&!p.boat&&p.store.wood>=4){p.store.wood-=4;p.boat=true;toast('🛶 水辺拠点で舟を発明！ 川と海を進める！')}}
function endTurn(){dice=0;reachable=[];reachPaths.clear();showHighlights();let finished=turn;turn=1-turn;if(finished===1){roundCount++;phaseIndex=roundCount%3;applyPhase()}reveal(players[turn]);updateFog();updateHud();focusPlayer(turn);if(mode==='com'&&turn===1)setTimeout(comTurn,650)}
async function comTurn(){if(mode!=='com'||turn!==1)return;busy=true;let n=rand(1,6);await animateDie(n);dice=n;reachable=getReachable(players[1],n);showHighlights();if(!reachable.length){busy=false;endTurn();return}reachable.sort((a,b)=>scoreTarget(players[1],b)-scoreTarget(players[1],a));busy=false;moveTo(reachable[0].x,reachable[0].y)}
function scoreTarget(p,c){let t=map[c.y][c.x],s=Math.random(),full=bagCount(p)>=BAG_MAX;if(full)s-=hdist(c.x,c.y,BASES[1][0],BASES[1][1])*.9;if(!full){if(t==='tree')s+=!p.fire?8:!p.boat?7:2;if(t==='rock'&&!p.fire)s+=7;if(t==='sand')s+=1}if(c.x===BASES[1][0]&&c.y===BASES[1][1]&&bagCount(p)>0)s+=10;if(p.fire&&!p.harbor&&isWaterside(c.x,c.y))s+=14;if(p.boat&&(t==='river'||t==='water'))s+=2;if(p.boat&&t==='goal')s+=40;if(!p.seen.has(key(c.x,c.y)))s+=2;return s}
function updateHud(){let p1=players[0],p2=players[1];document.getElementById('p1Inv').textContent=`🎒${bagCount(p1)}/${BAG_MAX} 🏕️🪵${p1.store.wood} 🪨${p1.store.stone}${p1.harbor?' 🌊':''}${p1.boat?' 🛶':''}`;document.getElementById('p2Inv').textContent=`🎒${bagCount(p2)}/${BAG_MAX} 🏕️🪵${p2.store.wood} 🪨${p2.store.stone}${p2.harbor?' 🌊':''}${p2.boat?' 🛶':''}`;document.getElementById('turnText').textContent=players[turn].name;document.getElementById('p1Card').classList.toggle('active',turn===0);document.getElementById('p2Card').classList.toggle('active',turn===1);document.getElementById('diceBtn').disabled=busy||dice>0||(mode==='com'&&turn===1);let p=players[turn],mn=document.getElementById('missionNow'),md=document.getElementById('missionNeed'),bag=document.getElementById('bagHud');if(bag)bag.textContent=`🎒 ${bagCount(p)}/${BAG_MAX}　🪵${p.bag.wood} 🪨${p.bag.stone} ⌛${p.bag.sand}${p.harbor?'　🌊🏕️':''}${p.boat?'　🛶':''}`;if(!p.fire){mn.textContent='🔥 火を起こせ';md.textContent='基地保管：木2 石1'}else if(!p.harbor){mn.textContent='🏕️ 水辺に拠点を作れ';md.textContent='川・海のとなりの陸地へ行こう'}else if(!p.boat){mn.textContent='🛶 舟をつくれ';md.textContent='基地保管：木4'}else{mn.textContent='⭐ 川と海を越えろ';md.textContent='水上では舟に変わる'}}
function win(){document.getElementById('winnerText').textContent=`${players[turn].name} 勝利！`;document.getElementById('winDialog').showModal()}let toastTimer;function toast(s){let e=document.getElementById('toast');e.textContent=s;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),1200)}
function pointerDown(e){if(busy)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,px:e.clientX,py:e.clientY,moved:false};canvas.setPointerCapture?.(e.pointerId)}function pointerMove(e){if(!drag||drag.id!==e.pointerId)return;let dx=e.clientX-drag.px,dy=e.clientY-drag.py;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>18)drag.moved=true;drag.px=e.clientX;drag.py=e.clientY;if(drag.moved){cameraGoal.x-=dx*.0042*camDistance;cameraGoal.z-=dy*.0048*camDistance;lookGoal.x-=dx*.0042*camDistance;lookGoal.z-=dy*.0048*camDistance}}function pointerUp(e){if(!drag||drag.id!==e.pointerId)return;let moved=drag.moved;drag=null;if(!moved&&!busy&&reachable.length){let r=canvas.getBoundingClientRect();pointer.x=((e.clientX-r.left)/r.width)*2-1;pointer.y=-((e.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(pointer,camera);let hits=raycaster.intersectObjects(colliders,false);for(const hit of hits){let{x,y}=hit.object.userData;if(reachable.some(q=>q.x===x&&q.y===y)){moveTo(x,y);break}}}}
function renderLoop(){function loop(){requestAnimationFrame(loop);let dt=Math.min(.033,clock.getDelta());camera.position.lerp(cameraGoal,1-Math.pow(.001,dt));lookNow.lerp(lookGoal,1-Math.pow(.001,dt));camera.lookAt(lookNow);let t=performance.now()*.001;if(riverMesh)riverMesh.material.roughness=.13+.025*Math.sin(t*1.8);for(let i=0;i<humans.length;i++)if(humans[i]?.userData.boat.visible)humans[i].userData.boat.rotation.z=Math.sin(t*2.4+i)*.025;renderer.render(scene,camera)}loop()}
