const N=16;let mode='com',turn=0,dice=0,reachable=[],busy=false;const players=[{name:'PLAYER 1',x:2,y:13,inv:{wood:0,stone:0,sand:0},fire:false,boat:false},{name:'COM',x:13,y:13,inv:{wood:0,stone:0,sand:0},fire:false,boat:false}];
const map=Array.from({length:N},(_,y)=>Array.from({length:N},(_,x)=>{if(x===0||y===0||x===15||y===15)return'water';if(y<4&&x>4&&x<12)return'mountain';if((x<4&&y<5)||(x>11&&y<5))return'water';return'grass'}));
[[3,12],[5,11],[7,13],[10,12],[12,10],[4,8],[8,7],[11,6],[6,4]].forEach(([x,y])=>map[y][x]='tree');[[4,11],[8,12],[11,11],[5,7],[9,6],[12,7]].forEach(([x,y])=>map[y][x]='rock');[[2,9],[13,9],[7,5],[10,5]].forEach(([x,y])=>map[y][x]='sand');[[6,4],[10,4]].forEach(([x,y])=>map[y][x]='pass');for(let y=1;y<5;y++)for(let x=1;x<4;x++)map[y][x]='water';map[2][2]='goal';for(let y=1;y<5;y++)for(let x=12;x<15;x++)map[y][x]='water';map[2][13]='goal';
const board=document.getElementById('board');function start(m){mode=m;players[1].name=m==='com'?'COM':'PLAYER 2';document.getElementById('p2Name').textContent=players[1].name;document.getElementById('titleScreen').style.display='none';document.getElementById('gameApp').classList.remove('game-hidden');resetGame()}document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>start(b.dataset.mode));document.getElementById('backToTitle').onclick=()=>{document.getElementById('gameApp').classList.add('game-hidden');document.getElementById('titleScreen').style.display='grid'};
function resetGame(){players[0].x=2;players[0].y=13;players[1].x=13;players[1].y=13;for(const p of players){p.inv={wood:0,stone:0,sand:0};p.fire=false;p.boat=false}turn=0;dice=0;reachable=[];busy=false;document.getElementById('winDialog').close?.();render();}
function terrainClass(t){return t}function tileIcon(t){return{water:'🌊',tree:'🌲',rock:'🪨',sand:'🏖️',mountain:'⛰️',pass:'🚩',goal:'⭐',grass:''}[t]||''}
function render(){board.innerHTML='';for(let y=0;y<N;y++)for(let x=0;x<N;x++){const t=map[y][x],el=document.createElement('button');el.className=`cell ${terrainClass(t)}`;el.dataset.x=x;el.dataset.y=y;el.innerHTML=`<span class="terrain-icon">${tileIcon(t)}</span>`;if(reachable.some(r=>r.x===x&&r.y===y)){el.classList.add('reachable');el.onclick=()=>moveTo(x,y)}const here=players.map((p,i)=>p.x===x&&p.y===y?i:-1).filter(i=>i>=0);if(here.length){const wrap=document.createElement('span');wrap.className='pawns';here.forEach(i=>{const p=document.createElement('span');p.className=`pawn3d ${i===0?'red':'blue'}`;wrap.appendChild(p)});el.appendChild(wrap)}board.appendChild(el)}updateHud()}
function updateHud(){document.getElementById('p1Inv').textContent=`木${players[0].inv.wood} 石${players[0].inv.stone} 砂${players[0].inv.sand}${players[0].boat?' 舟✓':''}`;document.getElementById('p2Inv').textContent=`木${players[1].inv.wood} 石${players[1].inv.stone} 砂${players[1].inv.sand}${players[1].boat?' 舟✓':''}`;document.getElementById('turnText').textContent=`${players[turn].name} の番`;document.getElementById('p1Card').classList.toggle('active',turn===0);document.getElementById('p2Card').classList.toggle('active',turn===1);document.getElementById('diceValue').textContent=dice||'-';document.getElementById('moveLeft').textContent=dice?`行ける場所が光っています`:'サイコロを振ろう';document.getElementById('diceBtn').disabled=busy||dice>0||(mode==='com'&&turn===1);const p=players[turn];document.getElementById('techFire').classList.toggle('done',p.fire);document.getElementById('techBoat').classList.toggle('done',p.boat)}
function canEnter(p,x,y,from){if(x<0||y<0||x>=N||y>=N)return false;const t=map[y][x];if(t==='water'||t==='goal')return p.boat;if(t==='mountain'){if(map[from.y][from.x]!=='pass'&&map[from.y][from.x]!=='mountain')return false}return true}
function getReachable(p,steps){const q=[{x:p.x,y:p.y,d:0}],seen=new Set([`${p.x},${p.y}`]),out=[];while(q.length){const cur=q.shift();if(cur.d===steps){if(cur.x!==p.x||cur.y!==p.y)out.push(cur);continue}for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const x=cur.x+dx,y=cur.y+dy,k=`${x},${y}`;if(seen.has(k)||!canEnter(p,x,y,cur))continue;seen.add(k);q.push({x,y,d:cur.d+1})}}return out}
document.getElementById('diceBtn').onclick=roll;function roll(){if(busy||dice)return;busy=true;let n=0,spins=0;const it=setInterval(()=>{n=1+Math.floor(Math.random()*6);document.getElementById('diceValue').textContent=n;if(++spins>8){clearInterval(it);dice=n;reachable=getReachable(players[turn],dice);busy=false;render();if(!reachable.length)setTimeout(endTurn,500)}},70)}
function moveTo(x,y){if(busy||!reachable.some(r=>r.x===x&&r.y===y))return;const p=players[turn];p.x=x;p.y=y;reachable=[];collect(p,x,y);autoCraft(p);render();if(map[y][x]==='goal'){win();return}setTimeout(endTurn,500)}
function collect(p,x,y){const t=map[y][x];if(t==='tree'){p.inv.wood+=2;toast(`${p.name} 木 +2`)}else if(t==='rock'){p.inv.stone+=2;toast(`${p.name} 石 +2`)}else if(t==='sand'){p.inv.sand+=2;toast(`${p.name} 砂 +2`)}}
function autoCraft(p){if(!p.fire&&p.inv.wood>=2&&p.inv.stone>=1){p.inv.wood-=2;p.inv.stone--;p.fire=true;toast(`🔥 ${p.name} が火を発明！`)}if(p.fire&&!p.boat&&p.inv.wood>=4){p.inv.wood-=4;p.boat=true;toast(`🛶 ${p.name} が舟を発明！ 海へ行ける！`)}}
function endTurn(){dice=0;reachable=[];turn=1-turn;render();if(mode==='com'&&turn===1)setTimeout(comTurn,650)}
function scoreTarget(p,c){const t=map[c.y][c.x];let s=Math.random();if(!p.fire){if(t==='tree')s+=7;if(t==='rock')s+=6}else if(!p.boat){if(t==='tree')s+=8}else{if(t==='goal')s+=30;if(t==='water')s+=2}const d=Math.min(Math.abs(c.x-2)+Math.abs(c.y-2),Math.abs(c.x-13)+Math.abs(c.y-2));if(p.boat)s+=10/(1+d);return s}
function comTurn(){if(turn!==1||mode!=='com')return;busy=true;let n=1+Math.floor(Math.random()*6);dice=n;reachable=getReachable(players[1],n);render();setTimeout(()=>{if(!reachable.length){busy=false;endTurn();return}reachable.sort((a,b)=>scoreTarget(players[1],b)-scoreTarget(players[1],a));busy=false;moveTo(reachable[0].x,reachable[0].y)},850)}
function win(){const d=document.getElementById('winDialog');document.getElementById('winnerText').textContent=`${players[turn].name} 勝利！`;d.showModal()}document.getElementById('playAgain').onclick=resetGame;document.getElementById('reset').onclick=resetGame;let tt;function toast(s){const e=document.getElementById('toast');e.textContent=s;e.classList.add('show');clearTimeout(tt);tt=setTimeout(()=>e.classList.remove('show'),1300)}render();