import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';

const N=16, HEX=1.0, HSTEP=.72, BAG_MAX=6;
const DIRS=[[1,0],[-1,0],[0,1],[0,-1],[1,-1],[-1,1]];
const BASES=[[2,13],[13,13]];
const phases=[
 {name:'朝',sky:0xb8d8e5,fog:0xa9c5ca,hemi:1.45,sun:2.1,sunColor:0xffd4a0,exposure:1.02},
 {name:'昼',sky:0x8fc6e3,fog:0x9bbfc8,hemi:1.7,sun:3.4,sunColor:0xfff0d0,exposure:1.08},
 {name:'晩',sky:0x24314d,fog:0x38485b,hemi:.72,sun:1.15,sunColor:0xff9360,exposure:.86}
];
const players=[
 {name:'PLAYER 1',x:2,y:13,bag:{wood:0,stone:0,sand:0},store:{wood:0,stone:0,sand:0},fire:false,boat:false,seen:new Set()},
 {name:'COM',x:13,y:13,bag:{wood:0,stone:0,sand:0},store:{wood:0,stone:0,sand:0},fire:false,boat:false,seen:new Set()}
];
let mode='com',turn=0,dice=0,busy=false,overview=false,seed=1,phaseIndex=0,turnCount=0;
let map=[],heightMap=[],reachable=[],reachPaths=new Map(),drag=null;
let terrain=[],colliders=[],resources=[],highlights=[],humans=[],bases=[],gridLines=[],dieGroup=null,riverMesh=null;
const canvas=document.getElementById('game3d'),world=document.getElementById('world'),loading=document.getElementById('loading'),errorEl=document.getElementById('webglError');
let renderer,scene,camera,raycaster,pointer=new THREE.Vector2(),clock=new THREE.Clock(),sun,hemi;
let cameraGoal=new THREE.Vector3(),lookGoal=new THREE.Vector3(),lookNow=new THREE.Vector3(),camDistance=13;

boot();
function boot(){try{if(!document.createElement('canvas').getContext('webgl2'))throw new Error('WebGL2 unavailable');init3D();bindUI();renderLoop();loading.classList.add('hidden')}catch(e){console.error(e);loading.classList.add('hidden');errorEl.textContent='3D表示を開始できませんでした: '+e.message;errorEl.classList.remove('hidden')}}
function init3D(){renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(42,1,.1,120);raycaster=new THREE.Raycaster();hemi=new THREE.HemisphereLight(0xe8f5ff,0x243324,1.5);scene.add(hemi);sun=new THREE.DirectionalLight(0xffefd2,3.0);sun.position.set(-11,20,8);sun.castShadow=true;sun.shadow.mapSize.set(1536,1536);sun.shadow.camera.left=-25;sun.shadow.camera.right=25;sun.shadow.camera.top=25;sun.shadow.camera.bottom=-25;sun.shadow.camera.far=70;scene.add(sun);const floor=new THREE.Mesh(new THREE.PlaneGeometry(100,100),new THREE.MeshStandardMaterial({color:0x294839,roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.46;floor.receiveShadow=true;scene.add(floor);applyPhase(true);resize();window.addEventListener('resize',resize)}
const MAT={grass:new THREE.MeshStandardMaterial({color:0x648c4e,roughness:.98}),valley:new THREE.MeshStandardMaterial({color:0x4b7240,roughness:1}),sand:new THREE.MeshStandardMaterial({color:0xd1b76d,roughness:1}),rock:new THREE.MeshStandardMaterial({color:0x817a6d,roughness:1}),mountain:new THREE.MeshStandardMaterial({color:0x817f77,roughness:1}),cliff:new THREE.MeshStandardMaterial({color:0x67655f,roughness:1}),pass:new THREE.MeshStandardMaterial({color:0x7c7f58,roughness:1}),goal:new THREE.MeshStandardMaterial({color:0x579d9a,roughness:.9}),water:new THREE.MeshPhysicalMaterial({color:0x327fa0,roughness:.16,transparent:true,opacity:.89,clearcoat:.7,clearcoatRoughness:.1}),river:new THREE.MeshPhysicalMaterial({color:0x4fa6c0,roughness:.13,transparent:true,opacity:.95,clearcoat:.75,clearcoatRoughness:.08})};
function rng(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}function rand(a,b){return a+Math.floor(rng()*(b-a+1))}function inside(x,y){return x>=0&&y>=0&&x<N&&y<N}function key(x,y){return `${x},${y}`}function hdist(a,b,c,d){let dx=c-a,dy=d-b;return(Math.abs(dx)+Math.abs(dy)+Math.abs(dx+dy))/2}function elevation(x,y){return heightMap[y]?.[x]??0}function pos(x,y){return new THREE.Vector3((x+y*.5)*HEX*1.73,0,y*HEX*1.5)}function topY(x,y){return elevation(x,y)*HSTEP}function bagCount(p){return p.bag.wood+p.bag.stone+p.bag.sand}function isBase(i,x,y){return BASES[i][0]===x&&BASES[i][1]===y}
function generateWorld(){seed=(Date.now()^Math.floor(Math.random()*1e9))>>>0;map=Array.from({length:N},()=>Array(N).fill('grass'));heightMap=Array.from({length:N},()=>Array(N).fill(1));for(let y=0;y<N;y++)for(let x=0;x<N;x++){let e=Math.min(x,y,N-1-x,N-1-y);if(e===0||(e===1&&rng()<.52)){map[y][x]='water';heightMap[y][x]=0}}for(let b=0;b<4;b++){let cx=rand(4,11),cy=rand(3,10),r=rand(2,4),peak=rand(3,5);for(let y=1;y<N-1;y++)for(let x=1;x<N-1;x++){let d=Math.hypot((x-cx)*.9,y-cy);if(d<r)heightMap[y][x]=Math.max(heightMap[y][x],Math.max(2,Math.round(peak-d/r*2.3)))}}let rx=rand(5,10);for(let y=1;y<N-1;y++){rx=Math.max(2,Math.min(N-3,rx+rand(-1,1)));map[y][rx]='river';heightMap[y][rx]=0;if(rng()<.28&&rx+1<N-1){map[y][rx+1]='river';heightMap[y][rx+1]=0}}for(let y=1;y<N-1;y++)for(let x=1;x<N-1;x++){if(map[y][x]==='river')continue;let h=elevation(x,y);if(h>=4)map[y][x]='mountain';else if(h===3)map[y][x]='cliff';else if(h===2&&rng()<.55)map[y][x]='valley'}for(const[sx,sy]of BASES)for(let y=sy-2;y<=sy+1;y++)for(let x=sx-2;x<=sx+2;x++)if(inside(x,y)){map[y][x]='grass';heightMap[y][x]=1}for(let i=0;i<17;i++)place('tree');for(let i=0;i<11;i++)place('rock');for(let i=0;i<9;i++)place('sand');let passes=0;for(let y=1;y<N-1;y++)for(let x=1;x<N-1;x++)if((map[y][x]==='mountain'||map[y][x]==='cliff')&&rng()<.13){map[y][x]='pass';heightMap[y][x]=Math.max(2,elevation(x,y));passes++}if(passes<2){map[5][5]='pass';heightMap[5][5]=2;map[6][10]='pass';heightMap[6][10]=2}for(const[gx,gy]of[[2,2],[13,2]]){for(let y=gy-1;y<=gy+1;y++)for(let x=gx-1;x<=gx+1;x++)if(inside(x,y)){map[y][x]='water';heightMap[y][x]=0}map[gy][gx]='goal';heightMap[gy][gx]=1}for(let i=0;i<2;i++){ensureNear(BASES[i][0],BASES[i][1],'tree');ensureNear(BASES[i][0],BASES[i][1],'rock')}}
function place(t){for(let i=0;i<100;i++){let x=rand(1,N-2),y=rand(1,N-2);if(map[y][x]==='grass'||map[y][x]==='valley'){map[y][x]=t;return}}}function ensureNear(sx,sy,t){for(let y=Math.max(1,sy-4);y<=Math.min(N-2,sy);y++)for(let x=Math.max(1,sx-4);x<=Math.min(N-2,sx+4);x++)if(map[y][x]===t)return;let x=Math.max(1,Math.min(N-2,sx+(rng()<.5?-2:2))),y=Math.max(1,sy-2);map[y][x]=t;heightMap[y][x]=1}
function clearWorld(){for(const o of [...terrain,...colliders,...resources,...highlights,...humans,...bases,...gridLines])scene.remove(o);if(riverMesh)scene.remove(riverMesh);if(dieGroup)scene.remove(dieGroup);terrain=[];colliders=[];resources=[];highlights=[];humans=[];bases=[];gridLines=[];riverMesh=null;dieGroup=null}
function buildWorld(){clearWorld();for(let y=0;y<N;y++)for(let x=0;x<N;x++){addTerrain(x,y);addCollider(x,y);addResource(x,y);addHighlight(x,y);addBorder(x,y)}addRiver();BASES.forEach((b,i)=>addBase(i,b[0],b[1]));humans=[makeHuman(0),makeHuman(1)];scene.add(...humans);updateHumans();reveal(players[0]);reveal(players[1]);updateFog()}
function terrainMaterial(t){if(t==='tree'||t==='rock')return MAT.grass;if(t==='sand')return MAT.sand;return MAT[t]||MAT.grass}
function addTerrain(x,y){let t=map[y][x],p=pos(x,y),h=topY(x,y);if(t==='water'){let m=new THREE.Mesh(new THREE.CylinderGeometry(1.15,1.2,.1,28),MAT.water.clone());m.position.set(p.x,.02,p.z);m.receiveShadow=true;m.userData={x,y,type:t};scene.add(m);terrain.push(m);return}let high=t==='mountain'||t==='cliff',topR=high?1.02:1.12,bottomR=t==='mountain'?1.42:t==='cliff'?1.3:1.18,base=Math.max(-.12,h-(t==='mountain'?2.05:t==='cliff'?1.65:.8)),depth=Math.max(.3,h-base+.18),sides=t==='mountain'?14:22,geo=new THREE.CylinderGeometry(topR,bottomR,depth,sides,3,false),mat=terrainMaterial(t).clone(),m=new THREE.Mesh(geo,mat);m.position.set(p.x,base+depth/2,p.z);m.castShadow=true;m.receiveShadow=true;m.userData={x,y,type:t};if(t==='mountain'){m.scale.y=1.16;m.rotation.y=(x*7+y*3)*.09}if(t==='sand'){m.scale.y=.9;addDunes(p.x,h+.11,p.z)}scene.add(m);terrain.push(m)}
function addDunes(x,y,z){for(let i=0;i<2;i++){let d=new THREE.Mesh(new THREE.TorusGeometry(.42+i*.08,.055,6,24,Math.PI),new THREE.MeshStandardMaterial({color:0xb99b59,roughness:1}));d.rotation.x=Math.PI/2;d.rotation.z=(i?.45:-.25);d.position.set(x+(i?-.25:.2),y+.03,z+(i?.1:-.1));d.castShadow=false;scene.add(d);resources.push(d)}}
function addCollider(x,y){let p=pos(x,y),g=new THREE.CylinderGeometry(.98,.98,.12,6);g.rotateY(Math.PI/6);let m=new THREE.Mesh(g,new THREE.MeshBasicMaterial({transparent:true,opacity:.002,depthWrite:false}));m.position.set(p.x,topY(x,y)+.09,p.z);m.userData={x,y};scene.add(m);colliders.push(m)}
function addBorder(x,y){let p=pos(x,y),shape=[];for(let i=0;i<7;i++){let a=Math.PI/6+i*Math.PI/3;shape.push(new THREE.Vector3(p.x+Math.cos(a)*.96,topY(x,y)+.19,p.z+Math.sin(a)*.96))}let geo=new THREE.BufferGeometry().setFromPoints(shape),line=new THREE.Line(geo,new THREE.LineBasicMaterial({color:0x263b2d,transparent:true,opacity:.5}));line.userData={x,y};scene.add(line);gridLines.push(line)}
function addHighlight(x,y){let p=pos(x,y),r=new THREE.Mesh(new THREE.RingGeometry(.62,.84,28),new THREE.MeshBasicMaterial({color:0xffdf56,transparent:true,opacity:0,side:THREE.DoubleSide,depthWrite:false}));r.rotation.x=-Math.PI/2;r.position.set(p.x,topY(x,y)+.17,p.z);r.userData={x,y};scene.add(r);highlights.push(r)}
function addResource(x,y){let t=map[y][x],p=pos(x,y),y0=topY(x,y)+.14;if(t==='tree'){let g=new THREE.Group();g.userData={x,y};for(let j=0;j<2;j++){let trunk=new THREE.Mesh(new THREE.CylinderGeometry(.08,.12,.55,7),new THREE.MeshStandardMaterial({color:0x60422e,roughness:1}));trunk.position.set((j-.5)*.28,.28,(j-.5)*.15);let crown=new THREE.Mesh(new THREE.ConeGeometry(.38,.85,8),new THREE.MeshStandardMaterial({color:j?0x2e6d3d:0x275f35,roughness:1}));crown.position.set((j-.5)*.28,.9,(j-.5)*.15);g.add(trunk,crown)}g.position.set(p.x,y0,p.z);g.traverse(o=>{if(o.isMesh)o.castShadow=true});scene.add(g);resources.push(g)}else if(t==='rock'){let r=new THREE.Mesh(new THREE.DodecahedronGeometry(.36,1),new THREE.MeshStandardMaterial({color:0x89857e,roughness:1}));r.position.set(p.x,y0+.28,p.z);r.scale.set(1.3,.75,1);r.castShadow=true;r.userData={x,y};scene.add(r);resources.push(r)}else if(t==='goal'){let g=new THREE.Group();g.userData={x,y};let pole=new THREE.Mesh(new THREE.CylinderGeometry(.05,.05,1.15,8),new THREE.MeshStandardMaterial({color:0xf4d65c}));pole.position.y=.58;let star=new THREE.Mesh(new THREE.OctahedronGeometry(.22),new THREE.MeshStandardMaterial({color:0xffe56b,emissive:0x7b5d00,emissiveIntensity:.5}));star.position.y=1.25;g.add(pole,star);g.position.set(p.x,y0,p.z);scene.add(g);resources.push(g)}}
function addRiver(){let pts=[];for(let y=0;y<N;y++){let xs=[];for(let x=0;x<N;x++)if(map[y][x]==='river')xs.push(x);if(xs.length){let x=xs.reduce((a,b)=>a+b,0)/xs.length,p=pos(x,y);pts.push(new THREE.Vector3(p.x,.065,p.z))}}if(pts.length>2){let curve=new THREE.CatmullRomCurve3(pts),geo=new THREE.TubeGeometry(curve,96,.31,12,false);riverMesh=new THREE.Mesh(geo,MAT.river);scene.add(riverMesh);const bankMat=new THREE.MeshStandardMaterial({color:0x8b7651,roughness:1});for(let s of [-1,1]){let bankPts=pts.map((p,i)=>new THREE.Vector3(p.x+s*.38,.055,p.z));let bcurve=new THREE.CatmullRomCurve3(bankPts),bank=new THREE.Mesh(new THREE.TubeGeometry(bcurve,72,.08,8,false),bankMat);scene.add(bank);resources.push(bank)}}}
function addBase(i,x,y){let p=pos(x,y),g=new THREE.Group();g.userData={base:true,owner:i,x,y};let pad=new THREE.Mesh(new THREE.CylinderGeometry(.72,.82,.18,10),new THREE.MeshStandardMaterial({color:i?0x335c91:0x8b433b,roughness:.9}));pad.position.y=.09;let tent=new THREE.Mesh(new THREE.ConeGeometry(.45,.78,4),new THREE.MeshStandardMaterial({color:i?0x567fb2:0xc06656,roughness:1}));tent.position.y=.55;tent.rotation.y=Math.PI/4;let crate=new THREE.Mesh(new THREE.BoxGeometry(.32,.28,.32),new THREE.MeshStandardMaterial({color:0x735336,roughness:1}));crate.position.set(.55,.18,.15);g.add(pad,tent,crate);g.position.set(p.x,topY(x,y)+.14,p.z);g.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});scene.add(g);bases.push(g)}
function makeHuman(i){let g=new THREE.Group(),shirt=new THREE.MeshStandardMaterial({color:i?0x4b87ea:0xe94f45,roughness:.88}),skin=new THREE.MeshStandardMaterial({color:0xe3ad87,roughness:.9}),torso=new THREE.Mesh(new THREE.CylinderGeometry(.16,.19,.52,8),shirt),head=new THREE.Mesh(new THREE.SphereGeometry(.16,12,8),skin),leg1=new THREE.Mesh(new THREE.CylinderGeometry(.055,.055,.36,7),shirt),leg2=leg1.clone(),bag=new THREE.Mesh(new THREE.BoxGeometry(.25,.32,.16),new THREE.MeshStandardMaterial({color:0x705235,roughness:1}));torso.position.y=.58;head.position.y=.99;leg1.position.set(-.09,.18,0);leg2.position.set(.09,.18,0);bag.position.set(0,.58,-.18);g.add(torso,head,leg1,leg2,bag);g.userData={leg1,leg2,bag};g.traverse(o=>{if(o.isMesh)o.castShadow=true});return g}
function updateHumans(){players.forEach((p,i)=>{let v=pos(p.x,p.y);humans[i].position.set(v.x,topY(p.x,p.y)+.18,v.z);let fill=bagCount(p)/BAG_MAX;humans[i].userData.bag.scale.set(1,1+.35*fill,1)})}
function reveal(p){for(let y=0;y<N;y++)for(let x=0;x<N;x++)if(hdist(p.x,p.y,x,y)<=5)p.seen.add(key(x,y))}
function updateFog(){let v=players[turn];for(const m of terrain){let{x,y,type}=m.userData,seen=v.seen.has(key(x,y)),near=hdist(v.x,v.y,x,y)<=5;m.visible=seen;if(m.material){m.material.transparent=!near||type==='water';m.material.opacity=near?(type==='water'?.89:1):(type==='water'?.36:.46);m.material.depthWrite=near&&type!=='water'}}for(const r of resources){let d=r.userData;if(d&&Number.isFinite(d.x))r.visible=v.seen.has(key(d.x,d.y))}for(const c of colliders)c.visible=v.seen.has(key(c.userData.x,c.userData.y));for(const l of gridLines){let{x,y}=l.userData;l.visible=v.seen.has(key(x,y));l.material.opacity=hdist(v.x,v.y,x,y)<=5?.5:.22}}
function bindUI(){document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>startGame(b.dataset.mode));document.getElementById('backToTitle').onclick=()=>{document.getElementById('gameApp').classList.add('game-hidden');document.getElementById('titleScreen').style.display='grid'};document.getElementById('reset').onclick=resetGame;document.getElementById('playAgain').onclick=resetGame;document.getElementById('diceBtn').onclick=roll;document.getElementById('overviewBtn').onclick=()=>{overview=!overview;overview?showOverview():focusPlayer(turn)};canvas.addEventListener('pointerdown',pointerDown);canvas.addEventListener('pointermove',pointerMove);canvas.addEventListener('pointerup',pointerUp);canvas.addEventListener('pointercancel',pointerUp)}
function startGame(m){mode=m;players[1].name=m==='com'?'COM':'PLAYER 2';document.getElementById('p2Name').textContent=players[1].name;document.getElementById('titleScreen').style.display='none';document.getElementById('gameApp').classList.remove('game-hidden');requestAnimationFrame(()=>{resize();resetGame()})}
function resetGame(){generateWorld();players.forEach((p,i)=>{p.x=BASES[i][0];p.y=BASES[i][1];p.bag={wood:0,stone:0,sand:0};p.store={wood:0,stone:0,sand:0};p.fire=false;p.boat=false;p.seen=new Set()});turn=0;dice=0;busy=false;overview=false;phaseIndex=0;turnCount=0;reachable=[];reachPaths.clear();let d=document.getElementById('winDialog');if(d.open)d.close();applyPhase(true);buildWorld();updateHud();focusPlayer(0,true);toast('🏕️ 基地から出発！')}
function applyPhase(instant=false){let p=phases[phaseIndex];scene.background=new THREE.Color(p.sky);scene.fog=new THREE.FogExp2(p.fog,.022);hemi.intensity=p.hemi;sun.intensity=p.sun;sun.color.setHex(p.sunColor);renderer.toneMappingExposure=p.exposure;document.getElementById('timeBadge')&&(document.getElementById('timeBadge').textContent=`${phaseIndex===0?'🌅':phaseIndex===1?'☀️':'🌙'} ${p.name}`)}
function focusPlayer(i=turn,instant=false){let p=players[i],v=pos(p.x,p.y),h=topY(p.x,p.y);lookGoal.set(v.x,h+.35,v.z);cameraGoal.set(v.x+camDistance*.68,7.2+camDistance*.2,v.z+camDistance*.82);if(instant){camera.position.copy(cameraGoal);lookNow.copy(lookGoal);camera.lookAt(lookNow)}document.getElementById('cameraLabel').textContent=`📍 ${p.name}`}
function showOverview(){let v=pos(7.5,7.5);lookGoal.set(v.x,1,v.z);cameraGoal.set(v.x+20,22,v.z+25);document.getElementById('cameraLabel').textContent='🗺️'}function resize(){let r=world.getBoundingClientRect();if(r.width<2||r.height<2)return;renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}
function canEnter(p,x,y,from){if(!inside(x,y))return false;let t=map[y][x],ft=map[from.y][from.x],dh=elevation(x,y)-elevation(from.x,from.y);if(t==='water'||t==='goal')return p.boat;if(t==='cliff'&&ft!=='pass')return false;if(Math.abs(dh)>=2&&t!=='pass'&&ft!=='pass')return false;if(t==='mountain'&&ft!=='pass'&&ft!=='mountain')return false;return true}
function getReachable(p,steps){let q=[{x:p.x,y:p.y,d:0,path:[]}],best=new Map([[key(p.x,p.y),0]]),out=[];reachPaths.clear();while(q.length){let cur=q.shift();if(cur.d===steps){if(cur.x!==p.x||cur.y!==p.y){out.push(cur);reachPaths.set(key(cur.x,cur.y),cur.path)}continue}for(const[dx,dy]of DIRS){let x=cur.x+dx,y=cur.y+dy,k=key(x,y);if(!canEnter(p,x,y,cur))continue;let nd=cur.d+1;if(best.has(k)&&best.get(k)<=nd)continue;best.set(k,nd);q.push({x,y,d:nd,path:[...cur.path,{x,y}]})}}return out}
async function roll(){if(busy||dice||(mode==='com'&&turn===1))return;busy=true;let n=rand(1,6);await animateDie(n);dice=n;reachable=getReachable(players[turn],n);showHighlights();busy=false;if(!reachable.length)setTimeout(endTurn,450)}
function dieTexture(n){let c=document.createElement('canvas');c.width=c.height=128;let g=c.getContext('2d');g.fillStyle='#fffaf0';g.fillRect(0,0,128,128);g.fillStyle='#181818';let P=[[64,64],[36,36],[92,92],[92,36],[36,92],[36,64],[92,64]],idx={1:[0],2:[1,2],3:[1,0,2],4:[1,3,4,2],5:[1,3,0,4,2],6:[1,5,4,3,6,2]}[n];for(const i of idx){g.beginPath();g.arc(P[i][0],P[i][1],11,0,Math.PI*2);g.fill()}let t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function makeDie(){if(dieGroup)scene.remove(dieGroup);dieGroup=new THREE.Group();let mats=[];for(let i=1;i<=6;i++)mats.push(new THREE.MeshStandardMaterial({map:dieTexture(i),roughness:.38}));let cube=new THREE.Mesh(new THREE.BoxGeometry(.88,.88,.88),mats);cube.castShadow=true;dieGroup.add(cube);scene.add(dieGroup);return cube}
function animateDie(n){return new Promise(resolve=>{let cube=makeDie(),p=players[turn],v=pos(p.x,p.y),base=topY(p.x,p.y),t0=performance.now(),dur=1050;dieGroup.position.set(v.x-1.1,base+2.3,v.z+.5);function step(now){let t=Math.min(1,(now-t0)/dur),hop=Math.abs(Math.sin(t*Math.PI*4.5))*(1-t)*1.7;dieGroup.position.set(v.x-1.1+t*3.25,base+.48+hop,v.z+.5+t*1.25);cube.rotation.x+=.26;cube.rotation.y+=.33;cube.rotation.z+=.21;if(t<1)requestAnimationFrame(step);else{setTimeout(()=>{scene.remove(dieGroup);dieGroup=null;resolve()},260)}}requestAnimationFrame(step)})}
function showHighlights(){let set=new Set(reachable.map(r=>key(r.x,r.y)));for(const h of highlights)h.material.opacity=set.has(key(h.userData.x,h.userData.y))?.82:0;if(reachable.length){let pts=reachable.map(r=>pos(r.x,r.y)),c=pts.reduce((a,b)=>a.add(b.clone()),new THREE.Vector3()).multiplyScalar(1/pts.length);lookGoal.set(c.x,1,c.z);cameraGoal.set(c.x+15,12,c.z+18)}}
async function moveTo(x,y){if(busy||!reachable.some(r=>r.x===x&&r.y===y))return;busy=true;let who=turn,p=players[who],path=reachPaths.get(key(x,y))||[{x,y}];reachable=[];showHighlights();for(const s of path){p.x=s.x;p.y=s.y;reveal(p);await walkStep(who,s.x,s.y);updateFog()}collect(p,x,y);if(isBase(who,x,y))depositAtBase(p);autoCraft(p);updateHumans();updateHud();busy=false;if(map[y][x]==='goal'){win();return}setTimeout(endTurn,450)}
function walkStep(i,x,y){return new Promise(resolve=>{let g=humans[i],from=g.position.clone(),v=pos(x,y),to=new THREE.Vector3(v.x,topY(x,y)+.18,v.z),t0=performance.now();function step(now){let t=Math.min(1,(now-t0)/290),e=t*t*(3-2*t);g.position.lerpVectors(from,to,e);g.userData.leg1.rotation.x=Math.sin(t*Math.PI*4)*.6;g.userData.leg2.rotation.x=-Math.sin(t*Math.PI*4)*.6;if(t<1)requestAnimationFrame(step);else{g.userData.leg1.rotation.x=g.userData.leg2.rotation.x=0;focusPlayer(i);resolve()}}requestAnimationFrame(step)})}
function collect(p,x,y){let t=map[y][x],item=t==='tree'?'wood':t==='rock'?'stone':t==='sand'?'sand':null;if(!item)return;if(bagCount(p)>=BAG_MAX){toast('🎒 リュックがいっぱい！ 基地へ戻ろう');return}p.bag[item]++;toast(`${item==='wood'?'🪵':item==='stone'?'🪨':'⌛'} リュックへ +1`)}
function depositAtBase(p){let n=bagCount(p);if(!n)return;for(const k of['wood','stone','sand']){p.store[k]+=p.bag[k];p.bag[k]=0}toast(`🏕️ 基地に ${n}個 保管！`)}
function autoCraft(p){if(!p.fire&&p.store.wood>=2&&p.store.stone>=1){p.store.wood-=2;p.store.stone--;p.fire=true;toast('🔥 基地で火を発明！')}if(p.fire&&!p.boat&&p.store.wood>=4){p.store.wood-=4;p.boat=true;toast('🛶 基地で舟を発明！')}}
function endTurn(){dice=0;reachable=[];reachPaths.clear();showHighlights();turnCount++;phaseIndex=turnCount%3;applyPhase();turn=1-turn;reveal(players[turn]);updateFog();updateHud();focusPlayer(turn);if(mode==='com'&&turn===1)setTimeout(comTurn,650)}
async function comTurn(){if(mode!=='com'||turn!==1)return;busy=true;let n=rand(1,6);await animateDie(n);dice=n;reachable=getReachable(players[1],n);showHighlights();if(!reachable.length){busy=false;endTurn();return}reachable.sort((a,b)=>scoreTarget(players[1],b)-scoreTarget(players[1],a));busy=false;moveTo(reachable[0].x,reachable[0].y)}
function scoreTarget(p,c){let t=map[c.y][c.x],s=Math.random(),full=bagCount(p)>=BAG_MAX;if(full)s-=hdist(c.x,c.y,BASES[1][0],BASES[1][1])*.9;if(!full){if(t==='tree')s+=!p.fire?8:!p.boat?7:2;if(t==='rock'&&!p.fire)s+=7;if(t==='sand')s+=1}if(c.x===BASES[1][0]&&c.y===BASES[1][1]&&bagCount(p)>0)s+=10;if(p.boat&&t==='goal')s+=40;if(!p.seen.has(key(c.x,c.y)))s+=2;return s}
function updateHud(){let p1=players[0],p2=players[1];document.getElementById('p1Inv').textContent=`🎒${bagCount(p1)}/${BAG_MAX} 🏕️🪵${p1.store.wood} 🪨${p1.store.stone}`;document.getElementById('p2Inv').textContent=`🎒${bagCount(p2)}/${BAG_MAX} 🏕️🪵${p2.store.wood} 🪨${p2.store.stone}`;document.getElementById('turnText').textContent=players[turn].name;document.getElementById('p1Card').classList.toggle('active',turn===0);document.getElementById('p2Card').classList.toggle('active',turn===1);document.getElementById('diceBtn').disabled=busy||dice>0||(mode==='com'&&turn===1);let p=players[turn],mn=document.getElementById('missionNow'),md=document.getElementById('missionNeed'),bag=document.getElementById('bagHud');if(bag)bag.textContent=`🎒 ${bagCount(p)}/${BAG_MAX}　🪵${p.bag.wood} 🪨${p.bag.stone} ⌛${p.bag.sand}`;if(!p.fire){mn.textContent='🔥 火を起こせ';md.textContent='基地保管：木2 石1'}else if(!p.boat){mn.textContent='🛶 舟をつくれ';md.textContent='基地保管：木4'}else{mn.textContent='⭐ 海の向こうへ';md.textContent='離島を見つけろ'}}
function win(){document.getElementById('winnerText').textContent=`${players[turn].name} 勝利！`;document.getElementById('winDialog').showModal()}let toastTimer;function toast(s){let e=document.getElementById('toast');e.textContent=s;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),1200)}
function pointerDown(e){if(busy)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,px:e.clientX,py:e.clientY,moved:false};canvas.setPointerCapture?.(e.pointerId)}function pointerMove(e){if(!drag||drag.id!==e.pointerId)return;let dx=e.clientX-drag.px,dy=e.clientY-drag.py;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>16)drag.moved=true;drag.px=e.clientX;drag.py=e.clientY;if(drag.moved){cameraGoal.x-=dx*.0052*camDistance;cameraGoal.z-=dy*.006*camDistance;lookGoal.x-=dx*.0052*camDistance;lookGoal.z-=dy*.006*camDistance}}function pointerUp(e){if(!drag||drag.id!==e.pointerId)return;let moved=drag.moved;drag=null;if(!moved&&!busy&&reachable.length){let r=canvas.getBoundingClientRect();pointer.x=((e.clientX-r.left)/r.width)*2-1;pointer.y=-((e.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(pointer,camera);let hits=raycaster.intersectObjects(colliders,false);for(const hit of hits){let{x,y}=hit.object.userData;if(reachable.some(q=>q.x===x&&q.y===y)){moveTo(x,y);break}}}}
function renderLoop(){function loop(){requestAnimationFrame(loop);let dt=Math.min(.033,clock.getDelta());camera.position.lerp(cameraGoal,1-Math.pow(.001,dt));lookNow.lerp(lookGoal,1-Math.pow(.001,dt));camera.lookAt(lookNow);let t=performance.now()*.001;if(riverMesh){riverMesh.material.roughness=.13+.025*Math.sin(t*1.8);riverMesh.material.color.offsetHSL(0,0,.015*Math.sin(t*2.2))}renderer.render(scene,camera)}loop()}
