import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';

const N=16, HEX=1.05, HSTEP=.62, DIRS=[[1,0],[-1,0],[0,1],[0,-1],[1,-1],[-1,1]];
let mode='com',turn=0,dice=0,busy=false,overview=false,seed=1,map=[],heightMap=[],reachable=[],reachPaths=new Map(),tileMeshes=[],terrainMeshes=[],resourceMeshes=[],highlightMeshes=[],playerGroups=[],dieGroup=null,dieRolling=false,drag=null,riverMesh=null;
const players=[{name:'PLAYER 1',x:2,y:13,inv:{wood:0,stone:0,sand:0},fire:false,boat:false,seen:new Set()},{name:'COM',x:13,y:13,inv:{wood:0,stone:0,sand:0},fire:false,boat:false,seen:new Set()}];

const canvas=document.getElementById('game3d'),world=document.getElementById('world'),loading=document.getElementById('loading'),errorEl=document.getElementById('webglError');
let renderer,scene,camera,raycaster,pointer=new THREE.Vector2(),sun,ambient,clock=new THREE.Clock(),targetLook=new THREE.Vector3(),cameraGoal=new THREE.Vector3(),lookGoal=new THREE.Vector3(),camDistance=13;
const materials={};

function webgl2(){const c=document.createElement('canvas');return !!c.getContext('webgl2')}
if(!webgl2()){loading.classList.add('hidden');errorEl.classList.remove('hidden');throw new Error('WebGL2 unavailable')}
init3D();bindUI();startRenderLoop();

function makeNoiseTexture(base='#6e9b58',dot='#517c43'){const c=document.createElement('canvas');c.width=c.height=256;const g=c.getContext('2d');g.fillStyle=base;g.fillRect(0,0,256,256);for(let i=0;i<1200;i++){g.globalAlpha=.08+Math.random()*.14;g.fillStyle=Math.random()>.5?dot:'#ffffff';const r=.5+Math.random()*2;g.beginPath();g.arc(Math.random()*256,Math.random()*256,r,0,Math.PI*2);g.fill()}g.globalAlpha=1;const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(3,3);t.colorSpace=THREE.SRGBColorSpace;return t}
function init3D(){renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;scene=new THREE.Scene();scene.background=new THREE.Color(0x9fb9c0);scene.fog=new THREE.FogExp2(0x95a9a8,.024);camera=new THREE.PerspectiveCamera(42,1,.1,100);raycaster=new THREE.Raycaster();ambient=new THREE.HemisphereLight(0xe5f5ff,0x30412f,1.45);scene.add(ambient);sun=new THREE.DirectionalLight(0xfff0cf,3.4);sun.position.set(-12,20,7);sun.castShadow=true;sun.shadow.mapSize.set(1536,1536);sun.shadow.camera.left=-24;sun.shadow.camera.right=24;sun.shadow.camera.top=24;sun.shadow.camera.bottom=-24;sun.shadow.camera.near=.5;sun.shadow.camera.far=60;sun.shadow.bias=-.0004;scene.add(sun);const ground=new THREE.Mesh(new THREE.PlaneGeometry(90,90),new THREE.MeshStandardMaterial({color:0x25483a,roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.5;ground.receiveShadow=true;scene.add(ground);createMaterials();resize();window.addEventListener('resize',resize);loading.classList.add('hidden')}
function createMaterials(){const mk=(c,r=.95,mapTex=null)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:0,map:mapTex});materials.grass=mk(0xffffff,.98,makeNoiseTexture('#6c9a56','#416b39'));materials.tree=materials.grass;materials.rock=mk(0x837b6a,.98,makeNoiseTexture('#928a77','#625c50'));materials.sand=mk(0xffffff,.98,makeNoiseTexture('#cdb879','#9c824c'));materials.valley=mk(0xffffff,.99,makeNoiseTexture('#507b47','#365f36'));materials.pass=mk(0x85835d,.98);materials.mountain=mk(0xffffff,.99,makeNoiseTexture('#aaa797','#747266'));materials.cliff=mk(0xffffff,1,makeNoiseTexture('#817d70','#555248'));materials.goal=mk(0x5faaa9,.9);materials.water=new THREE.MeshPhysicalMaterial({color:0x3c8aa5,roughness:.18,metalness:.02,transparent:true,opacity:.88,clearcoat:.55,clearcoatRoughness:.12});materials.river=new THREE.MeshPhysicalMaterial({color:0x59a9c0,roughness:.16,transparent:true,opacity:.94,clearcoat:.65,clearcoatRoughness:.1})}
function rng(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}function rand(a,b){return a+Math.floor(rng()*(b-a+1))}function inside(x,y){return x>=0&&y>=0&&x<N&&y<N}function key(x,y){return `${x},${y}`}function hdist(a,b,c,d){let dx=c-a,dy=d-b;return(Math.abs(dx)+Math.abs(dy)+Math.abs(dx+dy))/2}function hexPos(x,y,h=0){return new THREE.Vector3((x+y*.5)*HEX*1.72,h*HSTEP/2,y*HEX*1.5)}function elevation(x,y){return heightMap[y]?.[x]??0}

function generateWorld(){seed=(Date.now()^Math.floor(Math.random()*1e9))>>>0;map=Array.from({length:N},()=>Array(N).fill('grass'));heightMap=Array.from({length:N},()=>Array(N).fill(1));for(let y=0;y<N;y++)for(let x=0;x<N;x++){const edge=Math.min(x,y,N-1-x,N-1-y);if(edge===0||(edge===1&&rng()<.48)){map[y][x]='water';heightMap[y][x]=0}}for(let b=0;b<4;b++){let cx=rand(4,11),cy=rand(3,10),r=rand(2,4),peak=rand(3,5);for(let y=1;y<N-1;y++)for(let x=1;x<N-1;x++){let d=Math.hypot(x-cx,y-cy);if(d<r)heightMap[y][x]=Math.max(heightMap[y][x],Math.max(2,Math.round(peak-d/r*2)))}}let rx=rand(5,10);for(let y=1;y<N-1;y++){rx=Math.max(2,Math.min(N-3,rx+rand(-1,1)));map[y][rx]='river';heightMap[y][rx]=0;if(rng()<.18&&rx+1<N-1){map[y][rx+1]='river';heightMap[y][rx+1]=0}}for(let y=1;y<N-1;y++)for(let x=1;x<N-1;x++){if(map[y][x]==='river')continue;let h=heightMap[y][x];if(h>=4)map[y][x]='mountain';else if(h===3)map[y][x]='cliff';else if(h===2&&rng()<.5)map[y][x]='valley'}for(const[sx,sy]of[[2,13],[13,13]])for(let y=sy-2;y<=sy+1;y++)for(let x=sx-2;x<=sx+2;x++)if(inside(x,y)){map[y][x]='grass';heightMap[y][x]=1}for(let i=0;i<15;i++)placeResource('tree');for(let i=0;i<10;i++)placeResource('rock');for(let i=0;i<7;i++)placeResource('sand');let passes=0;for(let y=1;y<N-1;y++)for(let x=1;x<N-1;x++)if((map[y][x]==='cliff'||map[y][x]==='mountain')&&rng()<.12){map[y][x]='pass';heightMap[y][x]=Math.max(2,heightMap[y][x]);passes++}if(passes<2){map[5][5]='pass';heightMap[5][5]=2;map[6][10]='pass';heightMap[6][10]=2}for(const[gx,gy]of[[2,2],[13,2]]){for(let y=gy-1;y<=gy+1;y++)for(let x=gx-1;x<=gx+1;x++)if(inside(x,y)){map[y][x]='water';heightMap[y][x]=0}map[gy][gx]='goal';heightMap[gy][gx]=1}ensureNear(2,13,'tree');ensureNear(2,13,'rock');ensureNear(13,13,'tree');ensureNear(13,13,'rock')}
function placeResource(t){for(let i=0;i<100;i++){let x=rand(1,N-2),y=rand(1,N-2);if(map[y][x]==='grass'||map[y][x]==='valley'){map[y][x]=t;return}}}
function ensureNear(sx,sy,t){for(let y=Math.max(1,sy-4);y<=Math.min(N-2,sy);y++)for(let x=Math.max(1,sx-4);x<=Math.min(N-2,sx+4);x++)if(map[y][x]===t)return;let x=Math.max(1,Math.min(N-2,sx+(rng()<.5?-2:2))),y=Math.max(1,sy-2);map[y][x]=t;heightMap[y][x]=1}

function clearWorld(){for(const m of [...tileMeshes,...terrainMeshes,...resourceMeshes,...highlightMeshes])scene.remove(m);for(const g of playerGroups)scene.remove(g);if(dieGroup)scene.remove(dieGroup);if(riverMesh)scene.remove(riverMesh);tileMeshes=[];terrainMeshes=[];resourceMeshes=[];highlightMeshes=[];playerGroups=[];dieGroup=null;riverMesh=null}
function visualMaterial(t){if(t==='tree')return materials.grass;if(t==='rock')return materials.grass;if(t==='sand')return materials.sand;return materials[t]||materials.grass}
function buildWorld(){clearWorld();const colliderGeo=new THREE.CylinderGeometry(HEX,HEX,.12,6,1,false);colliderGeo.rotateY(Math.PI/6);for(let y=0;y<N;y++)for(let x=0;x<N;x++){const t=map[y][x],h=elevation(x,y),top=h*HSTEP,colliderMat=new THREE.MeshBasicMaterial({transparent:true,opacity:.002,depthWrite:false,color:0xffffff}),collider=new THREE.Mesh(colliderGeo,colliderMat),p=hexPos(x,y,h);collider.position.set(p.x,top+.05,p.z);collider.userData={x,y,tile:true,type:t};scene.add(collider);tileMeshes.push(collider);addNaturalPatch(t,x,y,h);addResourceObject(t,x,y,h);addHighlight(x,y,h)}buildRiver();playerGroups.push(makeHuman(0),makeHuman(1));scene.add(...playerGroups);updatePlayerMeshes();reveal(players[0]);reveal(players[1]);updateFog()}
function addNaturalPatch(t,x,y,h){if(t==='water')return;const top=h*HSTEP,low=Math.max(.08,top-(t==='mountain'?1.55:t==='cliff'?1.25:.65)),height=Math.max(.22,top-low+.22),topR=t==='mountain'?1.02:1.12,bottomR=t==='mountain'?1.28:t==='cliff'?1.24:1.18,geo=new THREE.CylinderGeometry(topR,bottomR,height,t==='mountain'?12:18,2,false),mat=visualMaterial(t).clone(),mesh=new THREE.Mesh(geo,mat),p=hexPos(x,y,h);mesh.position.set(p.x,low+height/2-.06,p.z);mesh.receiveShadow=true;mesh.castShadow=t!=='river';mesh.userData={x,y,natural:true,type:t};if(t==='mountain'){mesh.scale.y=1.05;mesh.rotation.y=(x+y)*.17}else if(t==='valley')mesh.scale.y=.82;scene.add(mesh);terrainMeshes.push(mesh)}
function buildRiver(){const pts=[];for(let y=0;y<N;y++){let xs=[];for(let x=0;x<N;x++)if(map[y][x]==='river')xs.push(x);if(xs.length){let x=xs.reduce((a,b)=>a+b,0)/xs.length,p=hexPos(x,y,0);pts.push(new THREE.Vector3(p.x,.08,p.z))}}if(pts.length>2){const curve=new THREE.CatmullRomCurve3(pts),geo=new THREE.TubeGeometry(curve,Math.max(24,pts.length*5),.28,8,false);riverMesh=new THREE.Mesh(geo,materials.river);riverMesh.receiveShadow=true;scene.add(riverMesh)}for(let y=0;y<N;y++)for(let x=0;x<N;x++)if(map[y][x]==='water'){const p=hexPos(x,y,0),m=new THREE.Mesh(new THREE.CylinderGeometry(1.18,1.2,.08,20),materials.water.clone());m.position.set(p.x,.015,p.z);m.receiveShadow=true;m.userData={x,y,natural:true,type:'water'};scene.add(m);terrainMeshes.push(m)}}
function addHighlight(x,y,h){const ring=new THREE.Mesh(new THREE.RingGeometry(.64,.83,32),new THREE.MeshBasicMaterial({color:0xffdf58,transparent:true,opacity:.0,side:THREE.DoubleSide,depthWrite:false}));ring.rotation.x=-Math.PI/2;ring.position.copy(hexPos(x,y,h));ring.position.y=h*HSTEP+.085;ring.userData={x,y};scene.add(ring);highlightMeshes.push(ring)}
function addResourceObject(t,x,y,h){const base=hexPos(x,y,h);base.y=h*HSTEP+.12;if(t==='tree'){const g=new THREE.Group();g.userData={x,y};const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.11,.16,.7,8),new THREE.MeshStandardMaterial({color:0x66462f,roughness:1}));trunk.position.y=.35;const crown1=new THREE.Mesh(new THREE.ConeGeometry(.48,.95,9),new THREE.MeshStandardMaterial({color:0x2c6337,roughness:1}));crown1.position.y=1.02;const crown2=new THREE.Mesh(new THREE.ConeGeometry(.37,.78,9),new THREE.MeshStandardMaterial({color:0x387545,roughness:1}));crown2.position.y=1.38;g.add(trunk,crown1,crown2);g.position.copy(base);g.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});scene.add(g);resourceMeshes.push(g)}else if(t==='rock'){const r=new THREE.Mesh(new THREE.DodecahedronGeometry(.38,0),new THREE.MeshStandardMaterial({color:0x8b877d,roughness:1}));r.scale.set(1.2,.7,1);r.position.copy(base).add(new THREE.Vector3(0,.28,0));r.castShadow=true;r.userData={x,y};scene.add(r);resourceMeshes.push(r)}else if(t==='goal'){const pole=new THREE.Mesh(new THREE.CylinderGeometry(.06,.06,1.2,8),new THREE.MeshStandardMaterial({color:0xf4d65c,roughness:.7}));pole.position.copy(base).add(new THREE.Vector3(0,.65,0));pole.castShadow=true;pole.userData={x,y};scene.add(pole);resourceMeshes.push(pole)}}
function makeHuman(i){const g=new THREE.Group(),shirt=new THREE.MeshStandardMaterial({color:i===0?0xe54f43:0x4a86e8,roughness:.85}),skin=new THREE.MeshStandardMaterial({color:0xe5b08a,roughness:.9});const body=new THREE.Mesh(new THREE.CapsuleGeometry(.16,.46,4,8),shirt);body.position.y=.54;const head=new THREE.Mesh(new THREE.SphereGeometry(.16,12,8),skin);head.position.y=1;const leg1=new THREE.Mesh(new THREE.CapsuleGeometry(.055,.32,3,6),shirt),leg2=leg1.clone();leg1.position.set(-.09,.13,0);leg2.position.set(.09,.13,0);g.add(body,head,leg1,leg2);g.userData={leg1,leg2};g.traverse(o=>{if(o.isMesh)o.castShadow=true});return g}
function updatePlayerMeshes(){players.forEach((p,i)=>{const v=hexPos(p.x,p.y,elevation(p.x,p.y));playerGroups[i].position.set(v.x,elevation(p.x,p.y)*HSTEP+.25,v.z)})}
function reveal(p){for(let y=0;y<N;y++)for(let x=0;x<N;x++)if(hdist(p.x,p.y,x,y)<=5)p.seen.add(key(x,y))}
function updateFog(){const v=players[turn];for(const m of terrainMeshes){let{x,y}=m.userData,seen=v.seen.has(key(x,y)),now=hdist(v.x,v.y,x,y)<=5;m.visible=seen;if(m.material){m.material.transparent=!now;m.material.opacity=now?(m.userData.type==='water'?.88:1):(m.userData.type==='water'?.38:.42);m.material.depthWrite=now}}for(const m of resourceMeshes){if(m.userData&&Number.isFinite(m.userData.x))m.visible=v.seen.has(key(m.userData.x,m.userData.y))}for(const m of tileMeshes)m.visible=v.seen.has(key(m.userData.x,m.userData.y))}

function bindUI(){document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>startGame(b.dataset.mode));document.getElementById('backToTitle').onclick=()=>{document.getElementById('gameApp').classList.add('game-hidden');document.getElementById('titleScreen').style.display='grid'};document.getElementById('reset').onclick=resetGame;document.getElementById('playAgain').onclick=resetGame;document.getElementById('diceBtn').onclick=roll;document.getElementById('overviewBtn').onclick=()=>{overview=!overview;overview?showOverview():focusPlayer(turn)};canvas.addEventListener('pointerdown',pointerDown);canvas.addEventListener('pointermove',pointerMove);canvas.addEventListener('pointerup',pointerUp);canvas.addEventListener('pointercancel',pointerUp);canvas.addEventListener('wheel',e=>{e.preventDefault();camDistance=THREE.MathUtils.clamp(camDistance+e.deltaY*.01,8,20);focusPlayer(turn)},{passive:false})}
function startGame(m){mode=m;players[1].name=m==='com'?'COM':'PLAYER 2';document.getElementById('p2Name').textContent=players[1].name;document.getElementById('titleScreen').style.display='none';document.getElementById('gameApp').classList.remove('game-hidden');resetGame()}
function resetGame(){generateWorld();players[0].x=2;players[0].y=13;players[1].x=13;players[1].y=13;for(const p of players){p.inv={wood:0,stone:0,sand:0};p.fire=false;p.boat=false;p.seen=new Set()}turn=0;dice=0;busy=false;overview=false;reachable=[];reachPaths.clear();document.getElementById('winDialog').close?.();buildWorld();updateHud();focusPlayer(0,true);toast('🌍 新しい世界')}
function focusPlayer(i=turn,instant=false){const p=players[i],center=hexPos(p.x,p.y,elevation(p.x,p.y));lookGoal.set(center.x,elevation(p.x,p.y)*HSTEP+.3,center.z);const ang=Math.PI*.22;cameraGoal.set(center.x+camDistance*Math.sin(ang),7.8+camDistance*.2,center.z+camDistance*Math.cos(ang));if(instant){camera.position.copy(cameraGoal);targetLook.copy(lookGoal)}document.getElementById('cameraLabel').textContent=`📍 ${p.name}`}
function showOverview(){let cx=hexPos(7.5,7.5,0);lookGoal.set(cx.x,0,cx.z);cameraGoal.set(cx.x+19,20,cx.z+23);document.getElementById('cameraLabel').textContent='🗺️'}function resize(){const r=world.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}
function canEnter(p,x,y,from){if(!inside(x,y))return false;let t=map[y][x],fromT=map[from.y][from.x],dh=elevation(x,y)-elevation(from.x,from.y);if(t==='water'||t==='goal')return p.boat;if(t==='cliff'&&fromT!=='pass')return false;if(Math.abs(dh)>=2&&t!=='pass'&&fromT!=='pass')return false;if(t==='mountain'&&fromT!=='pass'&&fromT!=='mountain')return false;return true}
function getReachable(p,steps){let q=[{x:p.x,y:p.y,d:0,path:[]}],best=new Map([[key(p.x,p.y),0]]),out=[];reachPaths.clear();while(q.length){let cur=q.shift();if(cur.d===steps){if(cur.x!==p.x||cur.y!==p.y){out.push(cur);reachPaths.set(key(cur.x,cur.y),cur.path)}continue}for(const[dx,dy]of DIRS){let x=cur.x+dx,y=cur.y+dy,k=key(x,y);if(!canEnter(p,x,y,cur))continue;let nd=cur.d+1;if(best.has(k)&&best.get(k)<=nd)continue;best.set(k,nd);q.push({x,y,d:nd,path:[...cur.path,{x,y}]})}}return out}
async function roll(){if(busy||dice||(mode==='com'&&turn===1))return;busy=true;document.getElementById('diceBtn').classList.add('rolling');const n=1+Math.floor(Math.random()*6);await animateDie(n);document.getElementById('diceBtn').classList.remove('rolling');dice=n;reachable=getReachable(players[turn],dice);highlightReachable();busy=false;if(!reachable.length)setTimeout(endTurn,450)}
function makeDie(){if(dieGroup)scene.remove(dieGroup);dieGroup=new THREE.Group();const geom=new THREE.BoxGeometry(.8,.8,.8),mats=[];for(let i=1;i<=6;i++)mats.push(new THREE.MeshStandardMaterial({map:dieTexture(i),roughness:.45}));const cube=new THREE.Mesh(geom,mats);cube.castShadow=true;dieGroup.add(cube);scene.add(dieGroup);return cube}
function dieTexture(n){const c=document.createElement('canvas');c.width=c.height=128;const g=c.getContext('2d');g.fillStyle='#fff7df';g.fillRect(0,0,128,128);g.fillStyle='#1d1b18';const P=[[64,64],[38,38],[90,90],[90,38],[38,90],[38,64],[90,64]];let idx={1:[0],2:[1,2],3:[1,0,2],4:[1,3,4,2],5:[1,3,0,4,2],6:[1,5,4,3,6,2]}[n];for(const i of idx){g.beginPath();g.arc(P[i][0],P[i][1],10,0,Math.PI*2);g.fill()}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function animateDie(result){return new Promise(resolve=>{let cube=makeDie(),p=players[turn],start=hexPos(p.x,p.y,elevation(p.x,p.y));dieGroup.position.set(start.x-1,elevation(p.x,p.y)*HSTEP+2.4,start.z+1);let t0=performance.now(),dur=900;dieRolling=true;function step(now){let t=Math.min(1,(now-t0)/dur),hop=Math.abs(Math.sin(t*Math.PI*4))*(1-t)*1.7;dieGroup.position.x=start.x-1+t*3.3;dieGroup.position.z=start.z+1+t*1.2;dieGroup.position.y=elevation(p.x,p.y)*HSTEP+.5+hop;cube.rotation.x+=.22;cube.rotation.y+=.28;cube.rotation.z+=.18;if(t<1)requestAnimationFrame(step);else{cube.rotation.set(0,0,0);dieRolling=false;setTimeout(()=>{scene.remove(dieGroup);dieGroup=null;resolve()},220)}}requestAnimationFrame(step)})}
function highlightReachable(){const set=new Set(reachable.map(r=>key(r.x,r.y)));for(const m of highlightMeshes){const on=set.has(key(m.userData.x,m.userData.y));m.material.opacity=on?.9:0;m.visible=on}if(reachable.length){let xs=reachable.map(r=>hexPos(r.x,r.y,elevation(r.x,r.y))),c=xs.reduce((a,b)=>a.add(b.clone()),new THREE.Vector3()).multiplyScalar(1/xs.length);lookGoal.copy(c);cameraGoal.set(c.x+15,12,c.z+18)}}
async function moveTo(x,y){if(busy||!reachable.some(r=>r.x===x&&r.y===y))return;busy=true;let who=turn,p=players[who],path=reachPaths.get(key(x,y))||[{x,y}];reachable=[];highlightReachable();for(const s of path){p.x=s.x;p.y=s.y;reveal(p);await walkStep(who,s.x,s.y);updateFog()}collect(p,x,y);autoCraft(p);updateHud();busy=false;if(map[y][x]==='goal'){win();return}setTimeout(endTurn,450)}
function walkStep(i,x,y){return new Promise(resolve=>{let g=playerGroups[i],from=g.position.clone(),v=hexPos(x,y,elevation(x,y)),to=new THREE.Vector3(v.x,elevation(x,y)*HSTEP+.25,v.z),t0=performance.now();function step(now){let t=Math.min(1,(now-t0)/260),e=t*t*(3-2*t);g.position.lerpVectors(from,to,e);g.userData.leg1.rotation.x=Math.sin(t*Math.PI*4)*.55;g.userData.leg2.rotation.x=-Math.sin(t*Math.PI*4)*.55;lookGoal.lerp(to,.15);if(t<1)requestAnimationFrame(step);else{g.userData.leg1.rotation.x=g.userData.leg2.rotation.x=0;focusPlayer(i);resolve()}}requestAnimationFrame(step)})}
function collect(p,x,y){let t=map[y][x];if(t==='tree'){p.inv.wood+=2;toast('🪵 +2')}else if(t==='rock'){p.inv.stone+=2;toast('🪨 +2')}else if(t==='sand'){p.inv.sand+=2;toast('砂 +2')}}
function autoCraft(p){if(!p.fire&&p.inv.wood>=2&&p.inv.stone>=1){p.inv.wood-=2;p.inv.stone--;p.fire=true;toast('🔥 火を発明！')}if(p.fire&&!p.boat&&p.inv.wood>=4){p.inv.wood-=4;p.boat=true;toast('🛶 舟を発明！')}}function endTurn(){dice=0;reachable=[];reachPaths.clear();turn=1-turn;reveal(players[turn]);updateFog();updateHud();focusPlayer(turn);if(mode==='com'&&turn===1)setTimeout(comTurn,650)}
async function comTurn(){if(mode!=='com'||turn!==1)return;busy=true;let n=1+Math.floor(Math.random()*6);await animateDie(n);dice=n;reachable=getReachable(players[1],n);highlightReachable();if(!reachable.length){busy=false;endTurn();return}reachable.sort((a,b)=>scoreTarget(players[1],b)-scoreTarget(players[1],a));busy=false;moveTo(reachable[0].x,reachable[0].y)}
function scoreTarget(p,c){let t=map[c.y][c.x],s=Math.random();if(!p.fire){if(t==='tree')s+=7;if(t==='rock')s+=6}else if(!p.boat){if(t==='tree')s+=8}else{if(t==='goal')s+=30;if(t==='water')s+=2}if(t==='pass')s+=2;if(!p.seen.has(key(c.x,c.y)))s+=2.5;return s}
function updateHud(){document.getElementById('p1Inv').textContent=`🪵${players[0].inv.wood} 🪨${players[0].inv.stone}${players[0].boat?' 🛶':''}`;document.getElementById('p2Inv').textContent=`🪵${players[1].inv.wood} 🪨${players[1].inv.stone}${players[1].boat?' 🛶':''}`;document.getElementById('turnText').textContent=players[turn].name;document.getElementById('p1Card').classList.toggle('active',turn===0);document.getElementById('p2Card').classList.toggle('active',turn===1);document.getElementById('diceBtn').disabled=busy||dice>0||(mode==='com'&&turn===1);let p=players[turn],mn=document.getElementById('missionNow'),md=document.getElementById('missionNeed');if(!p.fire){mn.textContent='🔥 火を起こせ';md.textContent='木 2　石 1'}else if(!p.boat){mn.textContent='🛶 舟をつくれ';md.textContent='木 4'}else{mn.textContent='⭐ 海の向こうへ';md.textContent='離島を見つけろ'}}
function win(){document.getElementById('winnerText').textContent=`${players[turn].name} 勝利！`;document.getElementById('winDialog').showModal()}let toastTimer;function toast(s){const e=document.getElementById('toast');e.textContent=s;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),1100)}
function pointerDown(e){if(busy)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,px:e.clientX,py:e.clientY,moved:false};canvas.setPointerCapture?.(e.pointerId)}function pointerMove(e){if(!drag||drag.id!==e.pointerId)return;let dx=e.clientX-drag.px,dy=e.clientY-drag.py;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>8)drag.moved=true;drag.px=e.clientX;drag.py=e.clientY;if(drag.moved){cameraGoal.x-=dx*.018*camDistance;cameraGoal.z-=dy*.022*camDistance;lookGoal.x-=dx*.018*camDistance;lookGoal.z-=dy*.022*camDistance}}function pointerUp(e){if(!drag||drag.id!==e.pointerId)return;let moved=drag.moved;drag=null;if(!moved&&!busy&&reachable.length){const r=canvas.getBoundingClientRect();pointer.x=((e.clientX-r.left)/r.width)*2-1;pointer.y=-((e.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObjects(tileMeshes,false);for(const hit of hits){let{x,y}=hit.object.userData;if(reachable.some(q=>q.x===x&&q.y===y)){moveTo(x,y);break}}}}
function startRenderLoop(){function loop(){requestAnimationFrame(loop);let dt=Math.min(.033,clock.getDelta());camera.position.lerp(cameraGoal,1-Math.pow(.001,dt));targetLook.lerp(lookGoal,1-Math.pow(.001,dt));camera.lookAt(targetLook);const t=performance.now()*.001;for(const m of terrainMeshes)if(m.userData.type==='water')m.material.roughness=.16+.035*Math.sin(t*1.4+m.position.x*.25);if(riverMesh){riverMesh.material.roughness=.12+.04*Math.sin(t*1.8)}for(const m of highlightMeshes)if(m.visible)m.rotation.z=t*.45;renderer.render(scene,camera)}loop()}