const N=16,TW=76,TH=38,STEP_H=22,ORIGIN_X=630,ORIGIN_Y=120;let mode='com',turn=0,dice=0,reachable=[],busy=false,map=[],heightMap=[],seed=0;const players=[{name:'PLAYER 1',x:2,y:13,inv:{wood:0,stone:0,sand:0},fire:false,boat:false},{name:'COM',x:13,y:13,inv:{wood:0,stone:0,sand:0},fire:false,boat:false}];
const board=document.getElementById('board'),shell=board.parentElement;let cameraLabel=document.createElement('div');cameraLabel.className='camera-label';shell.appendChild(cameraLabel);
function rng(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}function rand(a,b){return a+Math.floor(rng()*(b-a+1))}function inside(x,y){return x>=0&&y>=0&&x<N&&y<N}
function generateWorld(){seed=(Date.now()^Math.floor(Math.random()*1e9))>>>0;map=Array.from({length:N},()=>Array(N).fill('grass'));heightMap=Array.from({length:N},()=>Array(N).fill(1));for(let y=0;y<N;y++)for(let x=0;x<N;x++){let edge=Math.min(x,y,N-1-x,N-1-y);if(edge===0||(edge===1&&rng()<.55)){map[y][x]='water';heightMap[y][x]=0}}
 for(let b=0;b<4;b++){let cx=rand(4,11),cy=rand(3,10),r=rand(2,4),peak=rand(3,5);for(let y=1;y<N-1;y++)for(let x=1;x<N-1;x++){let d=Math.hypot(x-cx,y-cy);if(d<r){let h=Math.max(2,Math.round(peak-(d/r)*2));heightMap[y][x]=Math.max(heightMap[y][x],h)}}}
 let riverX=rand(5,10);for(let y=1;y<N-1;y++){riverX=Math.max(2,Math.min(N-3,riverX+rand(-1,1)));map[y][riverX]='river';heightMap[y][riverX]=Math.min(heightMap[y][riverX],1);if(rng()<.28&&riverX+1<N-1){map[y][riverX+1]='river';heightMap[y][riverX+1]=1}}
 for(let y=1;y<N-1;y++)for(let x=1;x<N-1;x++){if(map[y][x]==='river')continue;let h=heightMap[y][x];if(h>=4)map[y][x]='mountain';else if(h===3)map[y][x]='cliff';else if(h===2&&rng()<.45)map[y][x]='valley'}
 const starts=[[2,13],[13,13]];for(const[sx,sy]of starts){for(let y=sy-2;y<=sy+1;y++)for(let x=sx-2;x<=sx+2;x++)if(inside(x,y)){map[y][x]='grass';heightMap[y][x]=1}}
 for(let i=0;i<14;i++)placeResource('tree');for(let i=0;i<10;i++)placeResource('rock');for(let i=0;i<7;i++)placeResource('sand');
 let passes=0;for(let y=1;y<N-1;y++)for(let x=1;x<N-1;x++){if((map[y][x]==='cliff'||map[y][x]==='mountain')&&rng()<.12){map[y][x]='pass';heightMap[y][x]=Math.max(2,heightMap[y][x]);passes++}}if(passes<2){map[5][5]='pass';heightMap[5][5]=2;map[6][10]='pass';heightMap[6][10]=2}
 let goals=[[2,2],[13,2]];for(const[gx,gy]of goals){for(let y=gy-1;y<=gy+1;y++)for(let x=gx-1;x<=gx+1;x++)if(inside(x,y)){map[y][x]='water';heightMap[y][x]=0}map[gy][gx]='goal';heightMap[gy][gx]=1}
 ensureNearStart(2,13,'tree');ensureNearStart(2,13,'rock');ensureNearStart(13,13,'tree');ensureNearStart(13,13,'rock')}
function placeResource(type){for(let tries=0;tries<100;tries++){let x=rand(1,N-2),y=rand(1,N-2);if(map[y][x]==='grass'||map[y][x]==='valley'){map[y][x]=type;return}}}function ensureNearStart(sx,sy,type){for(let y=Math.max(1,sy-4);y<=Math.min(N-2,sy);y++)for(let x=Math.max(1,sx-4);x<=Math.min(N-2,sx+4);x++)if(map[y][x]===type)return;let x=Math.max(1,Math.min(N-2,sx+(rng()<.5?-2:2))),y=Math.max(1,sy-2);map[y][x]=type;heightMap[y][x]=1}
function elevationAt(x,y){return heightMap[y]?.[x]??0}function iso(x,y){let e=elevationAt(x,y);return{x:ORIGIN_X+(x-y)*TW/2,y:ORIGIN_Y+(x+y)*TH/2-e*STEP_H,e}}
function start(m){mode=m;players[1].name=m==='com'?'COM':'PLAYER 2';document.getElementById('p2Name').textContent=players[1].name;document.getElementById('titleScreen').style.display='none';document.getElementById('gameApp').classList.remove('game-hidden');resetGame()}document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>start(b.dataset.mode));document.getElementById('backToTitle').onclick=()=>{document.getElementById('gameApp').classList.add('game-hidden');document.getElementById('titleScreen').style.display='grid'};
function resetGame(){generateWorld();players[0].x=2;players[0].y=13;players[1].x=13;players[1].y=13;for(const p of players){p.inv={wood:0,stone:0,sand:0};p.fire=false;p.boat=false}turn=0;dice=0;reachable=[];busy=false;document.getElementById('winDialog').close?.();render(true);toast('🌍 新しい地形を生成しました！')}
function tileIcon(t){return{tree:'🌲',rock:'🪨',sand:'🏖️',mountain:'⛰️',cliff:'🧗',valley:'',pass:'🚩',goal:'⭐',river:'💧',water:'',grass:''}[t]||''}
function render(follow=false){board.innerHTML='';for(let y=0;y<N;y++)for(let x=0;x<N;x++){let t=map[y][x],pos=iso(x,y),el=document.createElement('button');el.className=`cell ${t}`;el.dataset.x=x;el.dataset.y=y;el.style.left=`${pos.x}px`;el.style.top=`${pos.y}px`;el.style.zIndex=String(100+x+y+pos.e*4);el.style.setProperty('--wallH',`${Math.max(8,pos.e*STEP_H)}px`);el.innerHTML=`<span class="tile-left"></span><span class="tile-right"></span><span class="tile-top"></span><span class="terrain-icon">${tileIcon(t)}</span>`;if(reachable.some(r=>r.x===x&&r.y===y)){el.classList.add('reachable');el.onclick=()=>moveTo(x,y)}let here=players.map((p,i)=>p.x===x&&p.y===y?i:-1).filter(i=>i>=0);if(here.length){let wrap=document.createElement('span');wrap.className='pawns';here.forEach(i=>{let q=document.createElement('span');q.className=`pawn3d ${i===0?'red':'blue'}`;wrap.appendChild(q)});el.appendChild(wrap)}board.appendChild(el)}updateHud();if(follow)requestAnimationFrame(()=>followPlayer(turn))}
function followPlayer(i=turn){let p=players[i],pos=iso(p.x,p.y),scale=window.innerWidth<560?.92:1.05,tx=shell.clientWidth/2-pos.x*scale,ty=shell.clientHeight*.56-pos.y*scale;board.style.transform=`translate(${tx}px,${ty}px) scale(${scale})`;cameraLabel.textContent=`📍 ${p.name}　高度 ${elevationAt(p.x,p.y)}`}
window.addEventListener('resize',()=>{if(!document.getElementById('gameApp').classList.contains('game-hidden'))followPlayer(turn)});
function updateHud(){document.getElementById('p1Inv').textContent=`木${players[0].inv.wood} 石${players[0].inv.stone} 砂${players[0].inv.sand}${players[0].boat?' 舟✓':''}`;document.getElementById('p2Inv').textContent=`木${players[1].inv.wood} 石${players[1].inv.stone} 砂${players[1].inv.sand}${players[1].boat?' 舟✓':''}`;document.getElementById('turnText').textContent=`${players[turn].name} の番`;document.getElementById('p1Card').classList.toggle('active',turn===0);document.getElementById('p2Card').classList.toggle('active',turn===1);document.getElementById('diceValue').textContent=dice||'-';document.getElementById('moveLeft').textContent=dice?'光っている立体マスを選ぼう':'サイコロを振ろう';document.getElementById('diceBtn').disabled=busy||dice>0||(mode==='com'&&turn===1);let p=players[turn];document.getElementById('techFire').classList.toggle('done',p.fire);document.getElementById('techBoat').classList.toggle('done',p.boat)}
function canEnter(p,x,y,from){if(!inside(x,y))return false;let t=map[y][x],fromT=map[from.y][from.x],dh=elevationAt(x,y)-elevationAt(from.x,from.y);if(t==='water'||t==='goal')return p.boat;if(t==='river')return true;if(t==='cliff'&&fromT!=='pass')return false;if(Math.abs(dh)>=2&&t!=='pass'&&fromT!=='pass')return false;if(t==='mountain'&&fromT!=='pass'&&fromT!=='mountain')return false;return true}
function getReachable(p,steps){let q=[{x:p.x,y:p.y,d:0}],seen=new Set([`${p.x},${p.y}`]),out=[];while(q.length){let cur=q.shift();if(cur.d===steps){if(cur.x!==p.x||cur.y!==p.y)out.push(cur);continue}for(const[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){let x=cur.x+dx,y=cur.y+dy,k=`${x},${y}`;if(seen.has(k)||!canEnter(p,x,y,cur))continue;seen.add(k);q.push({x,y,d:cur.d+1})}}return out}
document.getElementById('diceBtn').onclick=roll;function roll(){if(busy||dice)return;busy=true;let n=0,spins=0,it=setInterval(()=>{n=1+Math.floor(Math.random()*6);document.getElementById('diceValue').textContent=n;if(++spins>8){clearInterval(it);dice=n;reachable=getReachable(players[turn],dice);busy=false;render(true);if(!reachable.length)setTimeout(endTurn,500)}},70)}
function moveTo(x,y){if(busy||!reachable.some(r=>r.x===x&&r.y===y))return;let p=players[turn];p.x=x;p.y=y;reachable=[];collect(p,x,y);autoCraft(p);render(true);if(map[y][x]==='goal'){win();return}setTimeout(endTurn,650)}
function collect(p,x,y){let t=map[y][x];if(t==='tree'){p.inv.wood+=2;toast(`${p.name} 木 +2`)}else if(t==='rock'){p.inv.stone+=2;toast(`${p.name} 石 +2`)}else if(t==='sand'){p.inv.sand+=2;toast(`${p.name} 砂 +2`)}else if(t==='river')toast('💧 小川を渡った！')}
function autoCraft(p){if(!p.fire&&p.inv.wood>=2&&p.inv.stone>=1){p.inv.wood-=2;p.inv.stone--;p.fire=true;toast(`🔥 ${p.name} が火を発明！`)}if(p.fire&&!p.boat&&p.inv.wood>=4){p.inv.wood-=4;p.boat=true;toast(`🛶 ${p.name} が舟を発明！ 海へ行ける！`)}}
function endTurn(){dice=0;reachable=[];turn=1-turn;render(true);if(mode==='com'&&turn===1)setTimeout(comTurn,700)}
function scoreTarget(p,c){let t=map[c.y][c.x],s=Math.random();if(!p.fire){if(t==='tree')s+=7;if(t==='rock')s+=6}else if(!p.boat){if(t==='tree')s+=8}else{if(t==='goal')s+=30;if(t==='water')s+=2}if(t==='pass')s+=2;if(t==='river')s+=.5;let d=Math.min(Math.abs(c.x-2)+Math.abs(c.y-2),Math.abs(c.x-13)+Math.abs(c.y-2));if(p.boat)s+=10/(1+d);return s}
function comTurn(){if(turn!==1||mode!=='com')return;busy=true;dice=1+Math.floor(Math.random()*6);reachable=getReachable(players[1],dice);render(true);setTimeout(()=>{if(!reachable.length){busy=false;endTurn();return}reachable.sort((a,b)=>scoreTarget(players[1],b)-scoreTarget(players[1],a));busy=false;moveTo(reachable[0].x,reachable[0].y)},900)}
function win(){document.getElementById('winnerText').textContent=`${players[turn].name} 勝利！`;document.getElementById('winDialog').showModal()}document.getElementById('playAgain').onclick=resetGame;document.getElementById('reset').onclick=resetGame;let tt;function toast(s){let e=document.getElementById('toast');e.textContent=s;e.classList.add('show');clearTimeout(tt);tt=setTimeout(()=>e.classList.remove('show'),1300)}generateWorld();render();